packages/extension/src/languages/en.json
packages/extension/src/pages/sign/details-tab.tsx
packages/extension/src/pages/sign/index.tsx
packages/hooks/src/sign-doc/index.ts
packages/hooks/src/tx/fee.ts
packages/hooks/src/tx/types.ts

This PR handles the case where a transaction to be signed using the Keplr-supplied offline signer has a fee already set.
The supplied fee is displayed to the user in the signing screen with a warning that it was set by the calling application already and an option to switch to the Keplr fee selection buttons to override it.
I am unfamiliar with mobx so not sure I have approached the local-state handling of the details tab component the right way.
Please let me know if any adjustements/changes are needed.

Feature: Allow transactions to supply their own fee

---

docs/api/suggest-chain.md

I've been working with `experimentalSuggestChain` recently for a project for the interchain foundation and was confused by these docs, so this pr adds a little bit more specificity.
Added:
- More accurate definition for `bech32Config`
- I pulled this example from the [eMoney code](https://wallet.e-money.com/keplr), and it's working locally for me, but let me know if there is a more preferred way of doing this
- Copy and pastable code block
- I was expecting something like this when I first came to the page, it should make things a little easier for future developers

Makes experimentalSuggestChain docs more specific

---

packages/cosmos/src/account/index.ts

Closes #196 
Checking the presence of `code_hash` is only needed to avoid possible conflicts in case any other chain uses `base_account` to send data.
`code_hash` is just the hex representation of the account, used for smart contracts on `ethermint`

feature: ethermint/evmos account support

---

packages/extension/src/config.ts

Hi, I work at kava-labs. We are working on integrated the Keplr wallet into our webapp and we would like to specify the fee amounts for low, medium, and high within the keplr walllet extension.
It is unclear what the correct process is to get these updated. I've provided both the expected values below and a code change.
Expected Fee Amounts:
- Low: 0 KAVA (no fee)
- Medium: 0.001 KAVA
- High: 0.25 KAVA
@Thunnini @delivan Please let me know if you need anything else for this.

Update default kava fees amounts

---

packages/extension/src/config.ts

This is a PR with updated info on the suite of e-Money stablecoins. EDKK, ESEK, ENOK and ECHF have been added to the list.

e-money stablecoins

---

packages/extension/src/config.ts

Kava-Labs is upgrading our mainnet today. (release is almost complete at the time of writing this).
Previous Chain ID: `kava-8`
New Chain ID: `kava-9`
I will follow up with a comment on here once the update is complete so this can be reviewed and merged

update Kava chainId for mainnet upgrade

---

packages/stores/src/account/base.ts

Solves the below due to not properly getting `coinType`

Ethereum Keys - Fix coin type check on broadcast

---

packages/extension/src/config.ts

Evmos has 18 decimals and not 6 like other cosmos chains.
gas-prices `0.025` should be `25000000000`, etc
> Crypto.com Cronos uses `5000000000000basecro` as gas-prices

Scale evmos gas-prices

---

README.md
packages/stores/src/query/cosmos/distribution/index.ts
packages/stores/src/query/cosmos/distribution/params.ts
packages/stores/src/query/cosmos/distribution/types.ts
packages/stores/src/query/cosmos/queries.ts
packages/stores/src/query/cosmos/supply/inflation.ts

The earning rate for staking doesn't take into account inflation coins sent to the community pool. There's a community tax taken off newly minted coins before distribution to delegators.
Most chains have a small community tax rate (2%) so the difference isn't noticable. But recently kava changed to 80% which was throwing off the rate.
This PR adds an observable to fetch the community tax from the distribution module, and includes it in the rate calculation.
If the query fails it falls back to the the current calculation.
Changes introduced:
| chain       | current | new    |
|-------------|---------|--------|
| cosmos      | 15.46   | 15.15  |
| osmosis     | 72.41   | 72.41  |
| secret      | 24.57   | 24.08  |
| akash       | 33.31   | 32.64  |
| crypto      | 14.85   | 14.85  |
| …

Include community tax in staking APR

---

packages/background/src/keyring/keyring.ts
packages/extension/src/pages/main/account.module.scss
packages/extension/src/pages/main/account.tsx
packages/extension/src/pages/main/index.tsx
packages/stores/src/account/base.ts

Since Ledgers on Keplr are hard-coded to use the `coinType = 118`, we must disable them on Evmos to prevent users from using invalid address and getting funds stuck.

Disable ledger accounts for Ethereum chains

---

packages/extension/src/pages/access/style.module.scss

Issue:
Changes:
- `overflow-y:  auto` to not overflow 
- `margin-bottom: 0rem` to gain some additional space (don't think it affects anything visually)
- `border: 1px solid black` to draw attention to what is being approved/this being a container. I think it's important when it IS scrollable

fix: Do not overflow container when requesting access to multiple chains

---

packages/stores/src/query/cosmwasm/contract-query.ts

Update cosmwasm query path, reference [v0.24 CHANGELOG](https://github.com/CosmWasm/wasmd/blob/v0.24.0/CHANGELOG.md#v0240-2022-03-09)
Juno will updated to wasm v0.24 in the next software-upgrade.

Update cosmwasm REST query path

---

packages/mobile/src/screens/web/webpages/stargaze.tsx

Adds support for the stargaze webview to respect `playsinline` attributes on embedded videos.

Fix stargaze inline video playback

---

packages/stores/src/account/cosmos.ts

- Reimplement bug fix undone in [this PR](https://github.com/chainapsis/keplr-wallet/commit/ae1faa5b84a3cb5f68593b6473057bdec56f1413), presumably due to a merge error

Reimplement coinType derivation fix

---

packages/mobile/src/router/requester.ts
packages/mobile/src/stores/wallet-connect/msg-requester.ts

- #388 breaks `yarn typecheck` by omitting `KeplrError` handlers in `@keplr-wallet/mobile`

Add `KeplrError` handlers in `@keplr-wallet/mobile`

---

packages/extension/src/config.ts

@Thunnini After the Kava-10 upgrade on May 25th, few (if any) validators are accepting zero fee transactions. This results in users' transactions getting stuck in mempool. This update will prevent that from occurring.

Update Low and Average Fees for Kava

---

packages/extension/src/config.ts

@Thunnini  Kava did a mainnet upgrade today and this is the new chainId for transactions.
Can we also have the beta: true tag removed. I'm happy to add that to this PR now that launch is completed.

new kava chain id

---

packages/extension/src/config.ts

Update Regen 'low' gas price to 0.015uregen to match the default RPC node min-gas-price (i.e. make 'low' a usable option for regen).
Resolves #405

bump regen low gas price from 0.01 to 0.015 so it matches min default rpc node price

---

packages/extension/src/config.ts

Due to high network activity, Kava users have been seeing their transactions fail using the previous low and average gas price. 
@Thunnini

URGENT - Increase kava gas price step

---

packages/extension/src/config.ts

the next [Evmos upgrade](https://www.mintscan.io/evmos/proposals/29) will force the min-gas-prices:  `25000000000aevmos`

Update EVMOS min-gas-price

---

packages/mobile/android/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/Podfile.lock
packages/mobile/package.json
yarn.lock

The react-native async storage library has a size limit in Android by default. We can remove this limit by turning on the next option to use more recent implementation.
Recently, an error due to size limit continues to occur, so quickly bump the react-native async storage library and turn on the next option to solve this issue.
In order to maintain more major options such as sdk version, the most latest version of the react-native async storage library is not used yet.

Bump "react-native-async-storage" and turn on "next" option for android

---

packages/extension/src/components/form/fee-buttons/fee-buttons.module.scss
packages/extension/src/components/form/fee-buttons/fee-buttons.tsx
packages/extension/src/components/form/gas-form/auto.module.scss
packages/extension/src/components/form/gas-form/auto.tsx
packages/extension/src/components/form/gas-form/container.module.scss
packages/extension/src/components/form/gas-form/container.tsx
packages/extension/src/components/form/gas-form/index.ts
packages/extension/src/config.ui.ts
packages/extension/src/pages/ibc-transfer/index.tsx
packages/extension/src/pages/main/stake.tsx
packages/extension/src/pages/send/index.tsx
packages/extension/src/pages/sign/details-tab.tsx
packages/hooks/package.json
packages/hooks/src/tx/gas-simulator.ts
packages/hooks/src/tx/index.ts
packages/hooks/src/tx/types.ts
packages/stores/src/account/base.ts
packages/stores/src/account/cosmos.ts
packages/stores/src/account/cosmwasm.ts
packages/stores/src/account/index.ts
packages/stores/src/account/secret.ts
packages/stores/src/account/types.ts
packages/stores/src/account/utils.ts

KO:
Tx를 처리하기 위해 필요한 gas를 POST /cosmos/tx/v1beta1/simulate endpoint를 사용해서 simulation하는 기능을 추가한다.
Tx의 consumed gas가 gas limit(gas wanted)에 도달하는 즉시 tx가 실패하기 때문에 이 기능을 통해서 얻은 gas used를 tx에 그대로 사용하면 잠재적으로 약간의 gas 소모량 변화에도 tx가 실패할 수 있다. 그러므로 적당한 값 (gas adjustment)를 곱해서 사용해야한다.
- AccountStore에서 send...Msg 형태의 method로는 각이 안나와서 make...Tx 형태의 method들을 새롭게 만들었다. send...Msg 형태의 method는 deprecated 되었다.
- make...Tx 형태의 method는 simulate, simulateAndSend, send, sendWithGasPrice 함수를 반환한다.
- 웹페이지에서 사용할 때 가장 기본적인 형태는 아래와 같을듯...
```
const tx = accountInfo.cosmos.makeWithdrawDelegationRewardTx(
validatorAddresses
);
await tx.simulateAndSend({ gasAdjustment: 1.3 });
```
- 하지만 귀찮은 문제가... 이 기능을 cosmos-sdk@0.43부터 사용할 수 있다. 0.43 이전의 형태의 simulation 방식은 구현하기 귀찮은 요소들이 있어서 안했다. 결론적으로 케플러에서 integration된 체인들 기준으로 …

Implement the tx simulation for estimating gas

---

docs/api/README.md
packages/background/src/keyring/keyring.ts
packages/background/src/keyring/service.ts
packages/extension/src/pages/sign/adr-36.tsx
packages/extension/src/pages/sign/index.tsx
packages/provider-mock/src/mock.ts
packages/provider/src/core.ts
packages/provider/src/inject.ts
packages/provider/src/types/msgs.ts
packages/stores/src/core/interaction/sign.ts
packages/types/src/ethereum.ts
packages/types/src/index.ts
packages/types/src/wallet/keplr.ts
packages/wc-client/src/index.ts

Implement Ethereum signing for messages and transactions in a new core function, to empower Keplr users on Cosmos-based EVM-compatible chains such as Evmos.
DApp developers can use `signEthereum(...)` and increase their supported audience to include Keplr users, thereby benefitting all ecosystems involved.
**Implementation**
- Create a new type (`EthSignType`) to indicate the type of Ethereum signature
- Create a new core function to perform arbitrary Amino signing with Ethereum parameters
- Modify the UI displayed when signing for Ethereum
- Add Ethereum Message and Transaction signing capabilities to the keyring
- Add relevant error handling
**Testing**
- Tested transaction and message signatures for correctness against `ethersjs` in Typescript
- Tested the following instances for error …

Add Ethereum Message and Tx Signing

---

packages/extension/webpack.config.js

Because the size of popup.bundle.js is too large, `File is too large to parse.` error occurs when publishing to firefox add-ons.
To solve this problem, code splitting is introduced.
The size of background.bundle.js is also a bit large, but that's not a problem right now as it won't stretch any more.

Enable code splitting

---

packages/extension/src/components/address/index.tsx

`<Address />` component can be written as a hook without using the lifecycle of the react class component. so I suggest changing to functional component.

refactoring extension/<Address /> component with Functional Component

---

packages/background/src/chains/types.ts
packages/extension/src/config.ts
packages/extension/src/stores/root.tsx
packages/mobile/src/config.ts
packages/mobile/src/stores/root.tsx
packages/stores-etc/src/axelar/currency-registrar.ts
packages/stores-etc/src/axelar/index.ts
packages/stores-etc/src/axelar/token-info.ts
packages/stores-etc/src/axelar/types.ts
packages/stores-etc/src/index.ts
packages/stores-etc/src/queries.ts

Introduce experimental implementation of `AxelarEVMBridgeCurrencyRegistrar` which adds the currency from `/axelar/evm/v1beta1/token_info/${chain}?asset=${denom}` endpoint.
Only work with "axelar-evm-bridge" feature.

Add axelar evm bridge currency registrar

---

packages/extension/src/config.ts

This patch expands the token list and fees list for Gravity Bridge to include a few Ethereum based assets, to allow their use as fee tokens.

Allow ETH tokens to be used for g-bridge fees

---

packages/extension/src/config.ts
packages/mobile/src/config.ts

Adding Umee `feeCurrencies.gasPriceStep`.
For the upcoming Umee release we are setting a consensus level minimum gas-price = 0.05uumee. So each validator has to set his minimum gas price to at least `0.05uumee`.

Set Umee gas-price steps

---

packages/hooks/package.json
packages/hooks/src/tx/memo.ts

This patch prevents simple inclusion of a valid mnemonic in the memo field to prevent from accidental disclosure

fix: prevent inclusion of mnemonic in memo

---

packages/background/src/chains/service.ts
packages/background/src/index.ts

For most cases, webpage suggests chain and then requests permission to keplr. There are only a few cases where permission is not required after suggest chain (such as chain list).
Therefore, in order to reduce the required interactions with the user, the permission is given to the requested origin when the suggest chain is passed.

Make `suggestChain` grant the permission to origin at the same time

---

packages/background/src/permission/handler.ts
packages/background/src/permission/messages.ts
packages/background/src/permission/service.ts
packages/provider-mock/src/mock.ts
packages/provider/src/core.ts
packages/provider/src/inject.ts
packages/provider/src/types/msgs.ts
packages/types/src/wallet/keplr.ts
packages/wc-client/src/index.ts

@dongwu-kim 
When the #591 PR was proposed, there was no `getChainInfosWithoutEndpoints()` API.
The problem is that in the case of the `getChainInfosWithoutEndpoints()` API, the global permission is used, not the per-chain permission. However, the old interface is ambiguous to handle such permission because we have to specify the chain id.
To solve this problem, we slightly modify the `disable()` API interface. If chain ids are specified, only the permission of a specific chain is deleted. If undefined or an empty array, all permissions associated with the origin are removed.

Change `disable()` API interface

---

packages/background/src/keyring/handler.ts
packages/background/src/keyring/init.ts
packages/background/src/keyring/messages.ts
packages/background/src/keyring/service.ts
packages/extension/src/pages/setting/keyring/change/name.tsx
packages/provider-mock/src/mock.ts
packages/provider/src/core.ts
packages/provider/src/inject.ts
packages/provider/src/types/msgs.ts
packages/stores/src/core/keyring.ts
packages/types/src/wallet/keplr.ts
packages/wc-client/src/index.ts

- Provide `window.keplr.changeKeyRingName` method for the web app.
TODO 
--- 
1. Prevent flick when the extension popup opens. -> `unlock` popup has the same issue
2. Support to `wc-client` Keplr instance?

[Extension] Add `window.keplr.changeKeyRingName` API

---

packages/types/package.json
packages/types/src/enigma-utils.ts
packages/types/src/index.ts
packages/types/src/wallet/keplr.ts
packages/types/src/window.ts

The purpose of this PR is to fix a Dependabot alert, which has been around for almost half a year. 
> axios Inefficient Regular Expression Complexity vulnerability 
This `High` level vulnerability exists in the `secretjs` dependency. 
Newer versions of `secretjs` have resolved this issue, but they do not include the relevant TypeScript interfaces. 
Since `secretjs` dropped these interfaces and since these interfaces are the only reason to include this dependency, it makes sense to remove the dependency altogether. 
There are a few more `@keplr-wallet` packages which rely on these newly added `secretjs` interfaces. 
Once the types package has been updated, the other packages can remove `secretjs` and update the import path.
This change will resolve `High` level security vulnerability in …

Remove outdated dependency

---

packages/extension/src/components/form/ibc/channel-registrar.tsx

This PR improves the user experience when adding a new IBC connection. Users may find it intuitive to enter simply the channel-id number—rather than the entire string—and this change allows users to do so, while still accepting the previous method.
Since channel IDs are automatically derived in the form `channel-{N}` according to how many channels were previously present, we can prefix any numeric input with `channel-` to properly format it.
Docs: https://ibc.cosmos.network/main/ibc/overview.html
https://user-images.githubusercontent.com/11379797/210451931-5571f9a9-9e78-43f8-9c54-de7fbb7afc24.mov
https://user-images.githubusercontent.com/11379797/210451940-e19585df-0d9d-4a66-bd6d-cd17d0c39412.mov

Allow numeric value as input for IBC channel-id

---

packages/unit/src/decimal.spec.ts
packages/unit/src/decimal.ts

* Add `approxRoot(..)` to Dec. Inspired by Cosmos SDK [Decimal](https://github.com/osmosis-labs/cosmos-sdk/blob/5b0f9cfa4331ad3c64d9690318e4621b569b9a50/types/decimal.go#L419). Useful for calculating square root prices for concentrated liquidity simulations.
* Add convenience static members: `Dec.smallestDec`, `Dec.one`, `Dec.zero`. (Inspired by Apple's core graphics primitives)
From packages/unit, run `yarn test decimal` to confirm correctness.

Add `approxRoot()` to `Dec`

---

packages/background/src/keyring/service.ts
packages/cosmos/src/adr-36/amino.spec.ts
packages/cosmos/src/adr-36/amino.ts

#653
Chains like evmos/injective differ in how address is calculated from public key. So far, adr36 has not handled this. Since it is impossible to distinguish them by looking at the public key itself, this is solved by adding an "algo" parameter.

Add "algo" parameter to adr36 functions to handle "ethsecp256k1"

---

packages/extension/src/background.html
packages/extension/src/manifest.json
packages/extension/webpack.config.js

#690
There is a problem with the firefox addon store that it rejects to upload js file over 5mb. I briefly tested tree shaking, but it didn't help much to suppress the size below 5mb. To solve this problem, I took a look at metamask and found that I can put html into the background page.
Once I solved the problem in this way. It's not yet clear what to do with service worker when manifest v3 is reached.

Use background as "page" and apply code split to background bundle

---

packages/cosmos/src/stargate/wrapper/index.ts
packages/extension/src/pages/sign/index.tsx

#697
When fee grant module is used, sign doc includes granter field which pay fees instead of tx sender. However, Keplr blocks "Approve" button if tx sender doesn't have enough balances to send tx. And, it makes using fee grant module confusing.
To fix this problem, make the fee config skip balance check if granter is set.

Make the fee config skip balance check if granter is set

---

packages/cosmos/src/signing/encode.ts

#454 fixed certain character escaping that was causing problems when the memo field contained `&`, `<`, or `>`. Unfortunately, this is still an issue when these characters are included in message content (such as in a wasm execute message field) when in Amino signing contexts.
This was recently fixed in `@cosmjs/amino` in https://github.com/cosmos/cosmjs/pull/1388.
This PR fixes that here as well, properly escaping the stringified Amino sign doc.

Escape serialized Amino sign doc

---

packages/chain-validator/src/connection.ts
packages/stores/src/query/cosmos/status/index.ts

The tendermint changelog doesn't show it exactly, but it looks like the /status rpc response format has changed. The new version doesn't return the jsonrpc form.

Adjust newer response format of tendermint

---

packages/background/src/keyring/service.ts
packages/proto-types/proto-types-gen/proto/ibc/applications/transfer/v1/tx.proto
packages/stores/src/account/cosmos.ts

This PR adds the optional `memo` field on the `MsgTransfer` message which is necessary for EIP712 typed data for Injective when using Keplr and Ledger. 
Edit: I've reset the content of the `outputHash` file, thus the tests failing, if you think it should be updated let me know.

fix: memo field missing in MsgTransfer

---

packages/extension/src/pages/register/enable-chains/index.tsx

Add NextStepEvmChainItem compoent, It is only visible in the following situations
- `Keyring` is `Ledger type`
- `fallbackEthereumLedgerApp` is false

Add Next Step EVM chain item view

---

packages/chain-validator/src/feature.ts
packages/stores/package.json
packages/stores/src/account/cosmos.ts
packages/stores/src/account/types.ts
yarn.lock

In ibc-go v7, there is a bug which MsgTransfer not implement `LegacyMsg`.
And, it makes error like below
```
recovered: expected *legacytx.LegacyMsg when using amino JSON stack: goroutine 8036803 [running]: runtime/debug.Stack() runtime/debug/stack.go:24 +0x65 github.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x23894a0, 0xc0e4f9dff0}) github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:71 +0x27 github.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x23894a0?, 0xc0e4f9dff0?}) github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:39 +0x30 github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x23894a0, 0xc0e4f9dff0}, 0xc0984e42c0?) github.com/cosmos/cosmos-sdk@v0.47.3/baseapp/recovery.go:28 +0x37 …
```

ibc go v7 hot fix

---

packages/mobile/src/screens/web/webpages/stargaze.tsx

To distinguish whether the user is employing a standard browser or a wallet app with custom URL input, or if they are using Keplr, I need a way to identify them. Therefore, I kindly ask for your approval on this PR.
Also, I would appreciate it if you could let me know when this change is deployed (in Android and iOS environments). How can I receive this information?

Change Stargaze source

---

packages/provider-mock/src/mock.ts
packages/provider/src/core.ts
packages/provider/src/cosmjs.ts
packages/provider/src/inject.ts
packages/types/src/wallet/keplr.ts
packages/types/src/window.ts
packages/wc-client/src/index.ts

멀티시그에서 `getOfflineSigner` 로 서명할 때`preferNoSetMemo`, `disableBalanceCheck` 기능을 사용하기 위해
`getOfflineSigner` 메소드들에 signOptions 매개변수를 추가합니다.
멀티시그에서는 서명할 때 fee를 내지 않기 때문에 balance를 체크할 필요가 없습니다

Add signOptions parameter to `getOfflineSigner`

---

packages/mobile/src/components/modal/infoModal.tsx
packages/mobile/src/screen/home/available.tsx
packages/mobile/src/screen/home/components/token/index.tsx
packages/mobile/src/screen/home/staked.tsx

info modal을 스태이킹 탭에 추가
info moda 컴포넌트의 내용을 외부에서 받을수 있게 수정

[KM-17] 스테이킹 탭에 info modal 추가

---

packages/mobile/src/screen/governance/index.tsx
packages/mobile/src/screen/home/staked.tsx

프로포절이 0개인 체인 안보여주도록 수정
aprList가 useMemo가 걸려있었는데 이렇게 되면 aprlist 값 업데이트가 deps에 값보다 늦게 업데이트가 되면 aprlist가 변경이 안되므로
useMemo을 제거 해서 aprList가 observable 하게 수정함

fix apr bug and dont show zero proposal list 

---

packages/mobile/src/screen/governance/components/card.tsx
packages/mobile/src/screen/governance/utils.ts
packages/mobile/src/screen/home/staked.tsx
packages/mobile/src/screen/staking/dashboard/dashboard.tsx
packages/mobile/src/screen/staking/validator-detail/unbonding-card.tsx
packages/mobile/src/utils/format.ts

1. in days로 되어있는 텍스트를 -> days left로 변경
2. https://linear.app/chainapsis/issue/KM-71/intlformatdate-format=en-%EB%B2%84%EA%B7%B8-%EC%88%98%EC%A0%95%ED%95%98%EA%B8%B0 해당 이슈 수정
format : 'en'을 지우고 해당 테스트랑 같이 보여줄 수 있게 옵션 수정

[KM-71] 상대시간명 통일 작업 

---

packages/mobile/src/components/input/fee-control/transaction-fee-modal.tsx
packages/mobile/src/components/input/reciepient-input/address-book-modal.tsx
packages/mobile/src/components/modal/infoModal.tsx
packages/mobile/src/components/modal/modal.tsx
packages/mobile/src/screen/home/components/token-found-modal/index.tsx
packages/mobile/src/screen/home/components/token/index.tsx
packages/mobile/src/screen/sign/sign-modal.tsx

ce4dfbf21f16c1d3092b4a73041f1a1be5e5e6f8 : https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=c28207c17f89445e84a2b0b288fd80d3&pm=s 툴팁 아이콘 색상 변경
76b4a35f94aafcdb6116cef18bc8ef617661a5b2 : https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=f20c1724ae6a4da0902311cbfd4b1acf&pm=s info modal 패딩값 변경
e49692dde1b1f61da8127adede17d77d06ab3bdf : https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=a269454d973f407eb3d9ed8d7f7f79b2&pm=s 모달의 전반적인 타이틀과 text사이의 간격 조정함 
- 전반적인 간격을 조절 하기 위해서 baseModalTitle에 padding을 8을 준다음 그외의 모달 마다 다른 간격은 각 모달에서 조정 하도록 했습니다
paddingTop에는 10 바텀에는  8를 준 이유는 모달의 인디케이터 페딩이 10이고 디자인상 인디케이터 아래 패딩은 12여서 
해당 값을 조절 하기 위해서 paddingTop이 10입니다

디자인 QA 글로벌 적용

---

packages/mobile/src/components/button/button.tsx
packages/mobile/src/components/collapsible-list/collapsible-list.tsx
packages/mobile/src/components/input/text-input/text-input.tsx
packages/mobile/src/components/pageHeader/header.tsx
packages/mobile/src/components/rect-button/index.tsx
packages/mobile/src/components/text-button/text-button.tsx
packages/mobile/src/components/token-view/index.tsx
packages/mobile/src/screen/governance/components/card.tsx
packages/mobile/src/screen/governance/index.tsx
packages/mobile/src/screen/home/components/claim-all/index.tsx
packages/mobile/src/screen/home/components/token/index.tsx
packages/mobile/src/screen/setting/components/page-button/index.tsx
packages/mobile/src/screen/setting/components/setting-address-item/index.tsx
packages/mobile/src/screen/setting/screens/security/permission/index.tsx
packages/mobile/src/screen/setting/screens/token/add/index.tsx
packages/mobile/src/screen/setting/screens/token/manage/index.tsx
packages/mobile/src/screen/staking/components/validator-item/index.tsx
packages/mobile/src/screen/staking/dashboard/dashboard.tsx
packages/mobile/src/screen/staking/redelegate/index.tsx
packages/mobile/src/screen/staking/validator-detail/delegated-card.tsx
packages/mobile/src/screen/staking/validator-detail/index.tsx
packages/mobile/src/screen/staking/validator-detail/unbonding-card.tsx
packages/mobile/src/screen/wallet/select/index.tsx
packages/mobile/src/screen/web/components/header/index.tsx
packages/mobile/src/screen/web/index.tsx
packages/mobile/src/screen/web/webpage.tsx
packages/mobile/src/styles/index.tsx

3ee981fffab31b3e71f52ab6b8561cc2e1dbb6a6
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=1da44183faab42eebf3408bd4d594a8b&pm=s 해당이슈의 버튼 색상 변경
1fe64770a8d47a8acd8d7b4929a68ab7c3818b86
-> pressing 상태의 색상값을 하나 만들었습니다
e89bc036c63f34a28aac67a10ca59f8f4d171632
8b9b19ea09317be8ec8838b18a16cf34dea7c2ff
674a54b381a1482da8c21189695132b75e439f5a
-> main, select wallet의 카드들 color-card-default로 변경
07ca1e616fa6e74721c9be56cc5f1dda555f51eb
e9abeb0ca076fde4971a5cde3c2cd132af5d76ef
5b93ba3e671d4ae7ea6097440121ed80e36df983
dda17d680d6a58e6a0cf105f4963483704ce71fd
-> 각 커밋 제목에 맞는 페이지들의 카드들 color-card-default로 변경
card-default가 아닌데 변경된 스타일들은 해당 페이지의 디자인대로 약간의 색상을 같이 변경했습니다
83537093c270d1cc7333b9537dcb754f2b5234c5
-> 외부에서 들어온 웹뷰일때 home 아이콘 제거 
ex) vote에서 프로포절 디테일 …

[QA] 전반적인 card 색상 수정 및 기타 스타일 변경

---

packages/mobile/src/components/pageHeader/header-register.tsx
packages/mobile/src/navigation.tsx
packages/mobile/src/screen/register/components/register-container.tsx
packages/mobile/src/screen/register/connect-hardware/index.tsx
packages/mobile/src/screen/register/connect-ledger/index.tsx
packages/mobile/src/screen/register/enable-chains/index.tsx
packages/mobile/src/screen/register/intro-new-user/index.tsx
packages/mobile/src/screen/register/new-mnemonic/index.tsx
packages/mobile/src/screen/register/recover-mnemonic/index.tsx
packages/mobile/src/screen/register/verify-mnemonic/index.tsx

기존 헤더에 있던 step 스트링을 container 안으로 이동 했습니다

[KM-119] 기존 헤더에 있던 step 스트링을 container 안으로 이동 했습니다

---

packages/extension/src/stores/skip/route.ts
packages/extension/src/stores/skip/types.ts

We pushed a small additive change to the route response and to the swap operation object: 
* At the top level of the route response, we added `swap_price_impact_percent`
* We also add `price_impact_percent` in the swap operation object. This appears to cause some kind of type validation error in the widget. 
Our best guess is that there's some kind of strict validation taking place that's checking that the swap operation object matches specification exactly -- not allowing additional fields. 
I built the extension and tested this in Chrome + Firefox, and it fixed the problem in both.

Adding new fields for price impact to objects

---

packages/mobile/src/components/special-button/button.tsx
packages/mobile/src/components/special-button/types.ts
packages/mobile/src/screen/sign/sign-modal.tsx

AnimatedLinearGradient에서 width 100%를 줄 경우 제일위 부모인 AnimatedView가 아닌 그 위 부모의 width를 따라가서
일단 스페셜버튼에 width 100%를 필요할때만 줄수 있게 props로 외부 스타일을 받을수 있게 했습니다

[KM-127] approve 버튼 스페셜 버튼으로 교체

---

packages/mobile/src/hooks/notification/internal/provider.tsx
packages/mobile/src/hooks/notification/types.ts
packages/mobile/src/screen/tx-result/failed.tsx
packages/mobile/src/screen/tx-result/pending.tsx
packages/mobile/src/screen/tx-result/success.tsx

tx 결과페이지 에서 토스트를 보여주지 않게 notification에 disable 값을 추가 했습니다
pending 페이지에서 home으로 갈때 home이 렌더링이 안되어있을때 tx결과가 나오면 결과 페이지로 다시 이동 하는 버그가 있어서
페이지 이동중일때는 가지 않을수 있게 수정 하였습니다.

[KM-129] tx-result 페이지에서 toast 보여주지 않기

---

packages/mobile/src/components/pageHeader/header.tsx
packages/mobile/src/languages/en.json
packages/mobile/src/languages/index.tsx
packages/mobile/src/screen/governance/list/index.tsx
packages/mobile/src/screen/setting/screens/general/general.tsx
packages/mobile/src/screen/sign/sign-modal.tsx
packages/mobile/src/stores/ui-config/index.ts

896f6d8bc83fa86846db3e4c1205da7a8ae9696f
-> sign 페이지 text qa 적용
f75008114f75c6c906654dd11264999a91760498
-> https://www.notion.so/chainapsis/Mobile-2-0-QA-Table-68368a2934ca45d7a8e113adf790f478?p=1fce9f2630aa41818b7ef7296b0919b8&pm=s : 스크롤바 계속 보여주기 (android 일때만)
[6624414](https://github.com/chainapsis/keplr-wallet/pull/974/commits/662441477fc765e56c97c4dddb81159f274ae9f9)
-> proposals에서 refresh 했을때 색상 추가
[0ee2464](https://github.com/chainapsis/keplr-wallet/pull/974/commits/0ee24645893fd484f783570ded887c24e67e3f03)
-> language 버튼 setting에서 제거
[f4173ac](https://github.com/chainapsis/keplr-wallet/pull/974/commits/f4173acf80aa147aef1c8d596df2fd071d255fe7)
-> fiat가 작동하지 않는 버그수정
[79894d1](https://github.com/chainapsis/keplr-wallet/pull/974/commits/79894d1774ede9c36b6d0cf147efc02901a15466)
-> …

[QA]  기능qa와 sign페이지의 text qa 적용

---

packages/mobile/src/components/collapsible-list/collapsible-list.tsx
packages/mobile/src/components/modal/card/index.tsx
packages/mobile/src/components/modal/infoModal.tsx
packages/mobile/src/components/toggle/index.tsx
packages/mobile/src/hooks/confirm/provider.tsx
packages/mobile/src/screen/home/available.tsx
packages/mobile/src/screen/home/components/deposit-modal/copy-address-scene.tsx
packages/mobile/src/screen/home/index.tsx
packages/mobile/src/screen/setting/components/contract-address-book-modal/index.tsx

21b50dfd61858e3ed469d14481de89aee6edb715
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=53259a8f80ee40a7861f3c37c4473008&pm=s 해당 사항을 적용 했습니다 
메인에서 각 요소들의 간격이 12인것 같아서 gutter 자체를 12로 변경했습니다 
76d7859054cee3baa06f621c1cc31b056ed05417
-> collapse list에서 하단 view more 버튼의 크키를 디자인 대로 변경 했습니다
eb50803d34056aca3e6c40b8fc621b8d6166c8ea
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=a269454d973f407eb3d9ed8d7f7f79b2&pm=s 해당 qa에서 맨 아래 부분 적용 했습니다
7d4badaa2957b16d86d993255d0829bda8044811
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=1967cbe91c9d4772bad998684974406f&pm=s 토글 색상을 변경 했습니다
64c6c9e8bb99e969dfe223b45240f2ac74cad921 …

[QA] 디자인 qa들 적용

---

packages/extension/src/pages/sign/components/keystone/index.tsx
packages/extension/src/pages/sign/components/keystone/scan.tsx
packages/extension/src/pages/sign/cosmos/adr36.tsx
packages/extension/src/pages/sign/cosmos/tx/view.tsx
packages/extension/src/pages/sign/ethereum/view.tsx
packages/extension/src/pages/sign/utils/handle-cosmos-sign.ts
packages/extension/src/pages/sign/utils/keystone.ts

When sign with Keystone and error in some cases, the error message does not display.

fix: display error message of signing with Keystone

---

packages/mobile/src/components/page/scroll-view.tsx
packages/mobile/src/screen/home/components/looking-for-chains/index.tsx

60078b3c42f8b0474989378b4da8f7f94d1633d0
-> 안드로이드에서 input 포커스시 기종마다 스크롤이 다르게 내려 가는것 같아서 내려가는 높이를 여유있게 100을 할당했습니다
31b86f273153da804d5b413b004edf1f11a02bf3
-> 누락된 LookingForChains에서 enable 체인으로 가는 라우팅을 추가 했습니다

[QA] qa 사항 적용

---

packages/mobile/src/components/input/text-input/text-input.tsx
packages/mobile/src/languages/en.json
packages/mobile/src/screen/register/connect-hardware/index.tsx
packages/mobile/src/screen/register/finalize-key/index.tsx
packages/mobile/src/screen/register/recover-mnemonic/index.tsx

register 페이지의 현재 구현된 페이지의 text qa진행 및 finalize-key 애니메이션에서 밑의 progress 퍼센트 추가
디자인 qa이 적용
: https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=1bb5a93e330a475e8e9603b0aff2f536&pm=s
https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=1e07ce2c965a4b18ab2024934459ee43&pm=s

[QA] reigister 페이지의 Text qa 및 디자인 qa적용

---

packages/mobile/src/components/modal/infoModal.tsx
packages/mobile/src/screen/home/components/deposit-modal/copy-address-scene.tsx
packages/mobile/src/screen/home/staked.tsx
packages/mobile/src/screen/staking/components/validator-item/index.tsx
packages/mobile/src/screen/staking/dashboard/dashboard.tsx
packages/mobile/src/screen/staking/validator-detail/index.tsx

9890ccaec1c65835fb6e65c94f4bbdd6ea16cbe8
-> https://www.notion.so/chainapsis/Mobile-2-0-QA-Table-68368a2934ca45d7a8e113adf790f478?p=8eb923b2700a4b32be695e9bdf886e37&pm=s 
54c16093b4fdf4797346414f38a1af01027481b9 08abebce37df8ade59066a6c44553e036e8de457
-> 스테이킹한 자산이 0.000001 이하일때 `< 0.000001` 형태로 표시 
50641636f010e6dd06dfc45e5f32e651197b857d
-> 스테이킹 탭에서 에러가 발생한 token 아이템 클릭시 에러모달이 보일수 있게 수정
eacce1510523b866c7207d60b03608d0002f9355
-> 벨리데이터 디테일 페이지와 스테이킹 대시보드 페이지에서 스테이킹 뱃지 추가

[Fix] 기능 qa 사항들 수정

---

packages/mobile/src/languages/en.json
packages/mobile/src/languages/ko.json
packages/mobile/src/screen/governance/index.tsx

거버넌스 리스트 페이지에서 empty 텍스트 수정
suggest 체인은 vote에서 안보일수 있게 수정
https://www.notion.so/chainapsis/Mobile-2-0-QA-Table-68368a2934ca45d7a8e113adf790f478?p=c30ec33aa9964ed3b2d08da5663cfc01&pm=s
해당 이슈는 해당 체인이 체인레지스트리에서 등록할때 stakeCurrency에 이미지를 등록하지 않아서 발생하는 문제여서 안고치기로 했습니다

[KM-146] 거버넌스 페이지에서 empty text 수정, suggect체인은 vote에서 안보이게 수정

---

packages/mobile/src/components/drawer/index.tsx
packages/mobile/src/components/input/memo-input/index.tsx
packages/mobile/src/components/input/reciepient-input/index.tsx
packages/mobile/src/components/input/search-text-input/index.tsx
packages/mobile/src/components/input/text-input/text-input.tsx

16364f93210b1cab66d725d25c102a1892947c91
-> ios에서 lockwallet 버튼이 눌리지 않는 버그가 있어서 수정했습니다
추가로 lockWallet에 들어갔을때 가끔 바로 잠금이 풀린다고 해서  혹시 몰라 일단 lock에다  await을 추가 했습니다.
4385034c71e3a31e543f6275d6f0e0109634544e
-> https://www.notion.so/chainapsis/Mobile-2-0-QA-Table-68368a2934ca45d7a8e113adf790f478?p=f3b8fcad95744b4e8e970acde9b5a363&pm=s 해당 이슈해결

[QA] 약간의 버그 수정과 qa 적용

---

packages/mobile/src/components/image/index.tsx

token item에서 2 deps로 ChainImageFallback-> Image 컴포넌트로 가서 FastImage를 호출 할 경우 대체이미지가 안보이는 문제가 있었습니다
정확한 원리는 파악을 못하고 일단 FastImage를 ChainImageFallback에서 바로 쓰면 해결이 되서 일단 그렇게 처리를 했습니다

[QA] home에서 토큰 이미지에서 placeholder가 안보이는 버그 수정

---

packages/mobile/src/screen/governance/index.tsx
packages/mobile/src/screen/staking/dashboard/dashboard.tsx

거버넌스 페이지에서 스켈레톤이 안사라지는 버그를 수정 했습니다
- 스테이킹중인 체인이 많을경우 전체 체인에 대해서 isFetching을 검사하면 시간이 너무 오래 걸리는것 같아서 하나만 완료 돼도 보여줄수 있게 수정했습니다
staking 페이지에서 기존 isNotReady는 isFetching값을 사용하는데 해당값은 캐싱이 안되서 접근시 마다 다른 데이터들이 케싱이 되어있어도 스켈레톤이 보이는 문제가 있어서 로직을 수정 했습니다

[Fix] 거버넌스 페이지 로딩 버그 수정

---

packages/mobile/src/screen/register/recover-mnemonic/index.tsx
packages/mobile/src/screen/register/verify-mnemonic/index.tsx

https://www.figma.com/file/QcgTPzrxekdaH4gGrMEnRh/Mobile-2.0?node-id=7850:67443&mode=dev
해당 디자인에서 헤더와 가이드테스트 사이의 간격을 좀더 넓혀달라고 해서 적용했습니다
verify mnemonic에서도 비슷한 디자인이라서 여기도 간격을 넓히고, 기존 디자인에서 text가 center라서 수정했습니다

[QA] 레지스터 페이지에서 헤더와 가이드 텍스트 간격 추가

---

packages/mobile/src/screen/home/components/claim-all/index.tsx
packages/mobile/src/screen/setting/screens/security/security.tsx
packages/mobile/src/screen/staking/components/validator-card/index.tsx
packages/mobile/src/screen/staking/validator-detail/delegated-card.tsx

1. 익스텐션의 로직과 같을수 있게 모바일의 claim all 로직 수정
2. dydx의 경우 스테이킹 리워드를 usdc로 표기해야 돼서 벨리데이터 디테일 페이지, delegated card에서 dydx일때만 리워드를 usdc로 보여줄수 있게 수정
claim all 할때 dydx는 테스트 해봤는데 오스모의 경우 claim all을 할때 claim 될만큼 리워드를 가진 지갑이 없어서 테스트를 못했습니다

익스텐션과 로직이 맞을수 있게 claimAll 수정

---

packages/mobile/src/languages/en.json
packages/mobile/src/screen/home/components/claim-all/index.tsx
packages/mobile/src/screen/home/index.tsx
packages/mobile/src/screen/send/select-asset/index.tsx

자산이 없을시 send 버튼 비활성화 및 empty text 추가
https://chainapsis.slack.com/archives/C01RAHVLXFS/p1705310811263929 스레드에서 5번이슈
. https://www.notion.so/chainapsis/Claim-All-dYdX-USDC-dYdX-fb5b90801132440ebe0459d6a39730b5 이것도 USDC (dYdX)가 아니라 현재 USDC (Noble/channel-0)으로 뜨는 것 같습니당!
-> dydx로 보일수 있도록 수정 했습니다

[QA] 자산이 없을때 send 페이지 수정

---

packages/extension/src/languages/en.json
packages/extension/src/pages/setting/advanced/endpoint/index.tsx
packages/extension/src/pages/sign/cosmos/tx/view.tsx

- Add link button that open new tab of lava change endpoint site on change endpoint page
- Add guide box when send transaction using lava endpoint

[KEPLR-215] Add Lava endpoint views

---

apps/extension/src/pages/sign/components/message-item/index.tsx

Fix sign message icon space

---

apps/extension/src/components/address-book-modal/index.tsx

Changes:
1. Renamed `accountsSearchText` and `debounceAccountsSearchText` to `searchText` and `debounceTrimmedSearchText` respectively, in order to use them commonly in both the Contacts tab and My Account tab without declaring additional state variables.
2. Modified `searchText` to apply trimming when debounce is applied, eliminating the need to call a separate trim method.
3. In the Contacts tab, added logic so that when a search term is entered, the datas value is calculated to return wallet names or addresses that include the search term regardless of case (since EVM addresses may contain uppercase letters).

[KEPLR-301] Add search bar to contacts tab on address book modal

---

packages/hooks/src/tx/recipient.ts

Injective에서 recipient 값으로 hex 주소를 입력하면 hex 주소 검증대신 bech32 주소 검증이 실행되도록 수정했습니다.

[KEPLR-485] Disallow hex addresses in Injective

---

packages/hooks/src/tx/recipient.ts

evm compatible인 경우 주소 형식에 따라 hex address와 bech32 address 모두 검증이 가능해야 하는데 이 부분을 제가 간과했습니다. rawRecipient가 0x로 시작하고 hex to bech32 변환이 가능한 경우에만 hex address 검증을 실행하도록 수정했습니다.

Fix unable to validate bech32 address when the chain is evm compatible

---

apps/extension/src/stores/root.tsx
apps/mobile/src/stores/root.tsx

In version v2.12.0, the Shentu chain upgraded to Cosmos-SDK v0.50.8:
During this upgrade, the message type for bank send transactions changed from `bank/MsgSend` to `cosmos-sdk/MsgSend`, which is no longer compatible with the previous format.
Currently, using bank/MsgSend to send transactions will fail.
Support from Keplr is required to accommodate this change.

chore: Update Shentu chain bank send msgs type to 'cosmos-sdk/MsgSend'

---

packages/unit/src/int-pretty.spec.ts
packages/unit/src/int-pretty.ts

I found that the int pretty constructor ended up being a performance bottleneck in the Osmosis FE
This was due to our usage of Price pretty's, and every operation doing IntPretty clones.
This PR removes the Clone overhead, and removes many additional string operations + allocs from the constructor.
This was found to be a big speedup for Osmosis FE.
PR'd in case it helps you!

Speedup Int-Pretty constructor and Clone()

---

apps/extension/src/pages/main/available.tsx
apps/extension/src/pages/main/components/looking-for-chains/index.tsx

- home의 looking for a chain 섹션과 상단 섹션 사이의 여백 조정
- looking for a chain 텍스트 x축 패딩으로 0.375rem을 줘서 텍스트가 살짝 오른쪽으로 이동하도록 조정

[KEPLR-676] QA

---

packages/unit/src/int-pretty.spec.ts

This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `calcutation` to `calculation` x4
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

docs/api/README.md

This update addresses some small but important typos in the method names that affect the clarity and functionality of the API. 
- The method `signAnimo` was mistakenly written with an "o" instead of an "a". The correct name is `signAmino`, which aligns with the standard for signing messages in the Amino format.
- Similarly, `signArbitary` was incorrectly spelled, missing the "r" in "Arbitrary". The corrected method name is now `signArbitrary`.
These changes ensure the method names are correctly aligned with the API documentation and improve consistency across the codebase.

Fix typos in API method names Update README.md

---

apps/extension/src/components/transition/scene/internal/base.tsx

- 사이드 패널 너비가 늘어날 때, grid column의 너비가 같이 늘어나는데, 늘어난 너비가 자식 요소의 최소 너비로 간주되다 보니 1fr이 적용된 grid column의 너비가 늘어난 상태 그대로 유지되는 문제가 있습니다.
- 1fr이 결국 하나의 column만 사용하기 때문에, 자식 요소보다는 부모 요소의 너비에 따라 column의 너비가 변경되도록  `1fr`을 `100%`로 변경했습니다.
- `FixedWidthSceneTransition` 컴포넌트를 사용하는 다른 곳 (update node modal, register page)에서는 grid 열의 너비 자체가 변경될 일이 없기 때문에 문제가 되지 않습니다.

[KEPLR-691] Overflow on deposit modal

---

packages/background/src/keyring-cosmos/service.ts
packages/background/src/keyring-ethereum/service.ts
packages/chain-validator/src/feature.ts

Currently, for EVM chains, only explicit chainIDs are allowed.
we want to have Keplr+Ledger support for all dymension eco-system rollapps.
This PR add the `dymension-network` chain feature, to allow dymension chains to have Keplr+Ledger support

feat: added dymension-network chain feature

---

apps/extension/src/pages/send/amount/ibc-transfer/destination-chain-view.tsx
apps/extension/src/pages/send/amount/ibc-transfer/modal.tsx
apps/extension/src/pages/send/amount/index.tsx
apps/hooks-internal/src/ibc-swap/amount.ts
apps/mobile/src/screen/activities/msg-items/ibc-swap-refunded.tsx
apps/stores-internal/src/skip/ibc-pfm-transfer.ts
apps/stores-internal/src/skip/queries.ts
apps/stores-internal/src/skip/types.ts
packages/background/src/index.ts
packages/background/src/tx-ethereum/handler.ts
packages/background/src/tx-ethereum/init.ts
packages/background/src/tx-ethereum/messages.ts
packages/hooks/src/ibc/index.ts
packages/stores-eth/src/account/base.ts

1. send/amount 페이지에서 ibc button 을 클릭시 브릿지 가능한 요소 보여주기
2. 이더리움 체인 클릭시 hex주소로 설정 및 swap route 쿼리
3. 일반 이더리움 send에서 전송후 address book에 최근항목에 저장이 안되는 문제 수정 -> 8f2e3fe2a7f5b67e4255d1836f1b58bddfdab35a
현재 구현 안되어있는 사항
1. 실제 msg를 보내는 부분
2. ibc tranfer 이름 변경 필요
3. swap fee? 같은 실제 브릿지후 얼마가 되는지 가격 보여줘야함 
`destination-chain-view.tsx` 
- 외부에서 destination chain을 받고 그대로 보여주도록 수정 (bridge 목적 체인의 경우에는 channel이 없기때문에 상위 컴포넌트에서 해당 부분을 결정 할수 있게 수정)
`amount/ibc-transfer/modal.tsx`
- 목적 체인이 브릿지되거나 or ibc로 갈 수있고 특정 체인(noble)의 경우 2가지 종류의 체인을 한 모달에서 보여주기 위해서 NoneIBCBridgeInfo와 IBCChannel 타입을 받아서 사용 하도록 수정 
- queryIBCPacketForwardingTransfer으로 부터 브릿지 정보를 받아서 보여주도록 수정
- sendType이 bridge일 경우 ibcSwapConfg를 사용하도록 수정
`send/amount/index.tsx`
- 기존의 isIbcTrasfer을 send, ibc-transfer, bridge 3가지 경우를 대응 하기 위해서 sendType으로 수정 
- …

evm 브릿지 1차 pr

---

apps/extension/src/components/input/fee-control/index.tsx
apps/extension/src/components/input/fee-control/modal.tsx
apps/extension/src/pages/sign/components/fee-summary/index.tsx
apps/extension/src/pages/sign/ethereum/view.tsx
packages/stores-eth/src/account/base.ts

- 외부 요청을 통해 수수료 옵션이 설정된 경우, cosmos처럼 메시지를 보여주도록 추가
- fee selector를 통해 fee가 설정된 경우, 사용자가 변경한 수수료 옵션이 tx data에 반영되도록 수정
- 사용자에게 보여지는 evm fee 계산 방식 개선
- 외부 사이트 및 내부 요청(FeeSummary)을 통해 설정된 수수료를 보여주는 부분에서 사용되는 `feeConfig.fees[0]`는 `gasLimit` * `gasPrice`이므로, `l1DataFee`를 더해줘야 total fee를 보여줘야 합니다.
- `feeConfig.type`이 있는 경우: fee selector를 통해 fee tier를 선택하는 경우 및 `getFeeTypePrettyForFeeCurrency` 메서드를 사용해 수수료를 계산했을 때 fee는 `(gasLimit * gasPrice) + l1DataFee`이므로, 이를 고려한 total fee를 보여줘야 합니다.
- op stack l1DataFee를 가져올 때 proxy contract를 직접 호출하도록 변경
- upgrdeable contract의 구조상 proxy가 storage layer, implementation이 logic layer로 분리되어 있어서
- implementation contract를 호출하게 되면 storage 정보가 완전히 달라서 의도된 값을 가져올 수 없습니다.
- block gas limit를 넘으면 tx가 revert 되므로 이를 ui에서 고려 필요
- 외부 사이트에서 요청이 들어올 때 수수료를 설정해주는 경우 …

[KEPLR-720] Improve evm fee options

---

apps/extension/src/pages/main/components/claim-all/index.tsx

- chain registry의 Elys currency 항목에 EDEN 추가 및 익스텐션에서 ueden을 target asset으로 잡도록 추가

Enable to claim rewards on Elys network

---

docs/docs/intro/index.md
docs/docs/use-with/cosmjs.md
docs/docs/use-with/secretjs.md
docs/docusaurus.config.ts
docs/package.json
docs/sidebars.ts
docs/yarn.lock

- Some other docs, referring Keplr docs, still links to old page directory. Redirection config was set in this PR.
- Sidebar orders (Removed `Use with` category)
- Updated contents for CosmJS, SecretJS (polished expressions and improved structures)
needing to do the further updates such as Deeplink page, but I submitted changes for some parts of my lists firstly.
---
- [CosmJS page update](https://keplr-wallet-extension-git-fork-editaahn-edit-726f8a-chainapsis.vercel.app/api/use-with/cosmjs)
- [SecretJS page update](https://keplr-wallet-extension-git-fork-editaahn-edit-726f8a-chainapsis.vercel.app/api/use-with/secretjs)
- [Redirection test](https://keplr-wallet-extension-git-fork-editaahn-edit-726f8a-chainapsis.vercel.app/api): /api -> /api/intro
- If I find more to redirect, I'll update …

Docs redirection config & contents update

---

apps/extension/src/languages/en.json
apps/extension/src/languages/ko.json
apps/extension/src/languages/zh-cn.json
apps/extension/src/pages/send/amount/index.tsx
apps/hooks-internal/src/ibc-swap/amount.ts
apps/hooks-internal/src/ibc-swap/use.ts
apps/stores-internal/src/skip/ibc-swap.ts
apps/stores-internal/src/skip/msgs-direct.ts
apps/stores-internal/src/skip/route.ts
packages/background/src/tx-ethereum/messages.ts

- send페이지에서 bridge를 실행 하는 경우 skip를 통해서 swap을 허용 하지 않기위해서 allowSwaps와 smartSwapOptions를 IBCSwapAmountConfig, ObservableQueryIBCSwapInner, ObservableQueryMsgsDirectInner등에 추가
- bridge의 경우 기존 ibc처럼 다른 주소로 보낼수도 있기 때문에 getTx, getReadyTx에 customRecipient를 받도록 수정하고, 해당 값이 있을경우 chainIdsToAddresses리스트 에서 목적 체인의 주소를 Recipient로 수정 하도록 함
- amount 페이지에서 bridge의 경우 swap을 통해서 tx를 전송 하는 로직 추가 
- allowSwaps를 false로 지정 했을때 route에서 swap을 사용하는 경우 에러를 반환 하는 로직 추가
-실제 디자인에 맞춰서 ui 변경, keplr Fee나 브릿지 fee 보여주는 부분 구현 필요

bridge 전송 로직 추가 - 2 

---

apps/extension/package.json
apps/extension/src/config.ts
apps/extension/src/pages/main/available.tsx
apps/extension/src/pages/main/token-detail/address-chip/index.tsx
apps/extension/src/pages/main/token-detail/modal.tsx
apps/extension/src/stores/huge-queries/index.ts
apps/extension/src/stores/index.tsx
apps/extension/src/stores/root.tsx
packages/stores-bitcoin/.eslintignore
packages/stores-bitcoin/.prettierignore
packages/stores-bitcoin/jest.config.js
packages/stores-bitcoin/package.json
packages/stores-bitcoin/src/account/base.ts
packages/stores-bitcoin/src/account/index.ts
packages/stores-bitcoin/src/account/store.ts
packages/stores-bitcoin/src/index.ts
packages/stores-bitcoin/src/queries/balance.ts
packages/stores-bitcoin/src/queries/bitcoin-indexer.ts
packages/stores-bitcoin/src/queries/index.ts
packages/stores-bitcoin/src/queries/types.ts
packages/stores-bitcoin/tsconfig.json
packages/stores/src/chain/base.ts
packages/types/src/chain-info.ts
yarn.lock

- testnet, signet indexer url 추가
- currencies 필드 추가
> coinMinimalDenom은 ibc, erc20 같이 체인 이름 옆에 표시되도록 구성을 해보았는데, 따로 식별자를 추가하는 게 좋을까요?
- `BitcoinAccountStore`는 베이스만 잡아놓았습니다
- `ObservableBitcoinIndexerQuery` 정의
- `ObservableQueryBitcoinBalance` 구현
> balance 값은 우선 mempool에 있는 utxo도 포함하도록 계산했습니다
- bitcoin currencies 등록 가능하게 수정
- `HugeQueriesStore`에 `BitcoinQueriesStore` 추가
- 체인 및 btc 자산도 검색 가능하도록 수정

stores-bitcoin - balance query

---

apps/extension/src/components/divder/index.tsx
apps/extension/src/components/full-horizontal-silder/index.tsx
apps/extension/src/pages/earn/amount/index.tsx
apps/extension/src/pages/earn/components/description-modal.tsx
apps/extension/src/pages/earn/components/estimation-section.tsx
apps/extension/src/pages/earn/components/overview-balance-section.tsx
apps/extension/src/pages/earn/components/overview-claim-section.tsx
apps/extension/src/pages/earn/confirm-usdn-estimation/index.tsx
apps/extension/src/pages/earn/intro/index.tsx
apps/extension/src/pages/earn/overview/tutorial-modal/earn-claim-content.tsx
apps/extension/src/pages/earn/overview/tutorial-modal/index.tsx
apps/extension/src/pages/earn/overview/tutorial-modal/manage-earn-content.tsx
apps/extension/src/pages/earn/transfer/amount.tsx
apps/extension/src/pages/earn/transfer/intro.tsx
apps/extension/src/pages/earn/withdraw/amount.tsx
apps/extension/src/pages/main/components/available-tab-slide-list/index.tsx
apps/extension/src/pages/main/components/token/wrapper-with-bottom-tag.tsx
apps/extension/src/pages/main/token-detail/banners/earn-apy-banner.tsx
apps/extension/src/pages/send/select-asset/index.tsx

Home 토큰 목록 아이템의 EARN 뱃지는 제거 예정으로 확인해서 light mode 반영하지 않았습니다. (`EarnBadgeWrapper`)

Add styles for Earn light mode

---

apps/extension/src/pages/earn/amount/index.tsx
apps/extension/src/pages/earn/components/input.tsx
apps/extension/src/pages/earn/transfer/amount.tsx
apps/extension/src/pages/earn/withdraw/amount.tsx

변경 전
변경 후
변경 전은 number여서 decimal point(`.`)를 length로 인식 못함 -> input value.length에서 글자 길이를 받을 때 포함되지 않음

Reduce space between earn amount and denom

---

packages/stores-starknet/src/queries/erc20-contract-info.ts

- `0x01c8c5847ae848eabf909515338e74dadbc724f54c7735851c57ecfdf1319143` 이 토큰의 경우 응답값이 다음과 같이 반환되어서 익스텐션에서 토큰을 추가할 때 0으로 뜨는 문제가 있었습니다.
```
{
"result": [
"0x00",
"0x444f47",
"0x03"
]
}
```
- 16진수 문자열을 연결하여 디코딩할 수 있게 수정하였습니다.

Fix starknet erc20 symbol hex decoding

---

apps/extension/src/pages/main/components/token/index.tsx

Fix an issue that tooltip is hidden on asset list

---

apps/extension/src/stores/root.tsx
packages/background/src/interaction/foreground/handler.ts
packages/background/src/interaction/foreground/init.ts
packages/background/src/interaction/foreground/messages.ts
packages/background/src/interaction/foreground/service.ts
packages/background/src/interaction/service.ts
packages/router-extension/src/env/extension.ts
packages/stores-core/src/core/interaction/interaction.ts

원인
- startCheckPingOnUI
- interaction service에서 startCheckPingOnUI라는 메소드가 있는데 이 메소드는 interaction이 요청되었지만 popup 또는 side panel이 다 닫혀서 더 이상 처리할 수가 없는데 여러가지 이유로 interaction이 reject되지 않았을 경우 백그라운드에서 자동으로 reject 시키는 기능임
- 하지만 interaction이 연속적으로 요청되었을때 첫번째 interaction으로 popup이 열리고 유저가 approve를 눌렀을때 즉시 두번째 interaction이 요청되면 유저가 approve를 눌러서 팝업이 닫혔지만 startCheckPingOnUI에서 더 이상 인터렉션을  처리할 ui가 없다고 판단하고 두번째 interaction을 rejectAll 시켜버리는 문제가 있음
- 그래서 startCheckPingOnUI를 global하게 모든 interaction에 대해서 처리하는게 아니라 각각의 interaction id에 대해서 처리하도록 수정
- openPopupWindow
- 이름 그대로 popup을 여는 기능인데 팝업을 create를 시도하고 이미 팝업이 있으면 기존 팝업의 url을 업데이트하는 기능임
- 근데 테스트 해본 결과 연속적인 요청이 들어왔을때 create가 실제로 작동하지 않아도 오류를 throw하지 않음...
- env의 unstableOnClose 기능도 create가 실제로는 이루어지지 않았는데 이를 감지할 수 없기 때문에 tab이 존재하지 않아서 close로 인식되어서 잘못 발생하는 것으로 …

외부 서명 요청이 연속적으로 들어올 때 간헐적으로 reject 되는 현상

---

apps/extension/src/pages/bitcoin/components/input/amount-input/input.tsx
apps/extension/src/pages/main/components/token/index.tsx
apps/extension/src/stores/huge-queries/index.ts
packages/hooks-bitcoin/src/tx/fee.ts
packages/stores-bitcoin/src/account/base.ts

- 비트코인이 enable 되어 있으면 메인에서 밸런스가 0이더라도 보여주도록 수정
- TokenItem에서 체인 이름 + 태그 + Copy Address 버튼이 너무 길어지면 태그가 줄바꿈되도록 수정
- 비트코인 Send 페이지에서 max가 아니지만 max 수량과 비슷할 때 올바른 에러가 보이도록 수정

[QA] Support Bitcoin - QA 2

---

apps/extension/src/hooks/bitcoin/use-psbt-validate.ts

- `inputsToSign` 구성할 때 각 input에서 `sighashType`을 추출하여 추가 (unisat inscription/runes linsting/unlisting 동작 확인)
- fee validation 로직 제거 (totalInput > totalOutput)
- 유효한 서명을 받아서 보관해놨다가 나중에 사용하려는 용도로 특정 index에 서명이 필요한 입력을 배치해놓고 나머지는 더미 데이터로 채우는 경우, 입력의 합이 출력의 합보다 작아질 수 있으므로 fee validation이 불필요

Extract sigHashType from psbt and remove fee validation

---

packages/background/src/chains/service.ts

cosmos == cosmos-1 == cosmos-2
위의 세개는 같은 체인으로 취급되어야 함
비트코인을 추가하면서 getBaseChainId가 추가되었는데
getBaseChainId에는 chain identifier 개념이 적용되어 있지 않아서 수정
getBaseChainId에서 eip, bitcoin 주소 체계는 {identifier}-{version}의 형태가 절대로 될 수 없다고 가정하고
chainId를 바로 ChainIdHelper.parse()를 사용해서 비교하도록 수정

Apply `ChainIdHelper` to getBaseChainId

---

apps/extension/src/pages/earn/components/use-earn-bottom-tag.ts
apps/extension/src/pages/main/available.tsx
apps/extension/src/pages/main/components/token/index.tsx
apps/extension/src/pages/main/components/token/wrapper-with-bottom-tag.tsx

- (USDN 잔고가 존재할 경우) balance의 여러 IBC USDC 토큰 중 가장 상단의 것을 찾아 earn bottom tag에 USDN 잔고 노출
- USDN 잔고를 `balances: ViewToken[]`(UI에 노출되는 토큰 목록)으로부터 가져와서 ref에 저장
- 가장 상단의 USDC를 찾기 위해 `AvailableTabView` 컴포넌트의 balance 리스트를 순회하며 null일 경우에 ref에 저장
- keyring 교체시에 이전 계정의 ref가 그대로 남아있어 earn bottom tag에 이전 계정의 USDN 잔고가 노출됨
- 기존 구조상에서 `useEarnBottomTag` 안에서 keyring 교체를 감지하려면 balances가 바뀌었을 때 ref 값들을 초기화해줘야 하는데, 이렇게 변경할 시 home에서 USDC를 검색하면 `balances: ViewToken[]`에 USDN이 없어지고 그로 인해 earn bottom tag에 노출할 USDN 잔고 정보가 소실됨
`useEarnBottomTag` hook 리팩토링
- USDN 잔고는 balance 쿼리를 직접 사용
- keyring 변경시 query가 `useMemo`와 매끄럽게 통합되지 않는 문제로 인해 memoization 하지 않음
- `topUsdcToken`은 `getBottomTagInfoProps` 외부에서 계산해두고 재사용

Fix earn feature state management and bottom tag UI alignment

---

apps/extension/src/hooks/bitcoin/use-psbt-validate.ts
apps/extension/src/pages/bitcoin/send/index.tsx
apps/extension/src/pages/bitcoin/sign/tx/view.tsx
packages/hooks-bitcoin/src/tx/psbt-simulator.ts

- 동일한 주소 형식, 동일한 금액으로 번갈아 send 요청을 실행하면 이전에 캐시된 psbt를 불러오는 문제
1. sendBitcoin 요청으로 1차적으로 bc1p...0x 주소로 1000 satoshi를 보내는 요청을 실행
2. 서명 페이지에서 reject하고 이번에는 bc1p...dc 주소로 1000 satoshi를 보내는 요청을 실행
3. 2번의 경우 1번에서 캐시된 Psbt가 불러와지면서 recipient 주소가 bc1p...0x로 처리되는 문제가 발생
4. 내부 send page에서도 동일하게 발생
- psbt simulator key에 address prefix를 사용해서 native-segwit인지 taproot인지만 구분하게 해서 주소가 변경될 때마다 state를 생성하지 않도록 하려는 의도였지만, 키가 중복됨으로 인해 의도치 않은, 캐시된 Psbt를 불러오는 문제가 발생하는 것을 확인했습니다.
- psbt simulator key에 address prefix만 사용했던 것을 주소 전체를 집어넣도록 수정
- sendBitcoin 요청으로 외부에서 들어오는 요청의 경우, simulator key에 요청 id를 추가로 포함하도록 수정
- `sendBitcoin` 요청에서 `isFetchingUTXOs`가 false인 경우에만 시뮬레이션이 실행되도록 수정
- 기존에는 `availableUTXOs`의 값이 재계산되면서 시뮬레이션이 재실행되어 화면에 표시되는 값이 계속 변경됨
- `usePsbtsValidate` 훅에서 `psbtsHexes`의 변경을 감지하고 검증 로직을 재실행할 수 있도록 수정

Prevent unintended cached psbt to be loaded with enhanced simulator key

---

apps/extension/src/analytics-amplitude.ts
apps/extension/src/pages/ibc-swap/select-asset/index.tsx
apps/extension/src/pages/main/available.tsx
apps/extension/src/pages/main/components/deposit-modal/copy-address-scene.tsx
apps/extension/src/pages/main/components/looking-for-chains/index.tsx
apps/extension/src/pages/manage-view-asset-token-list/index.tsx
apps/extension/src/pages/register/enable-chains/index.tsx
apps/extension/src/pages/send/select-asset/index.tsx

**Token**
- `click_token_item_search_results_available_tab`
- `click_token_item_search_results_select_asset_send`
- `click_token_item_search_results_select_asset_ibc_swap`
- `click_token_item_search_results_manage_view_asset`
**Chain**
- `click_looking_for_chain_search_results_available_tab`
- `click_looking_for_chain_search_results_deposit_modal`
- `click_copy_address_item_search_results_deposit_modal`
- `click_chain_item_search_results_register`
**공통**
- `query`: 검색어
- `searchResultCount`: 검색 결과의 전체 항목 개수
- `index`: 선택된 항목이 검색 결과의 전체 항목 중 몇 번째인지
- `upperItems`: 선택된 항목의 위 3개의 fields를 각각 join한 array
- ex. Token - `["usdc/injective", "usdc/osmosis", "usdc/noble"]`
- `lowerItems`: 선택된 항목의 아래 3개의 fields를 각각 join한 array
**Token**
- `coinDenom`
- `chainName`
**Chain**
- `chainName`

Log clicks on search results to Amplitude

---

apps/extension/src/pages/register/enable-chains/index.tsx

`searchedNonNativeChainInfos`를 빼먹어서 XRPL EVM Testnet의 index가 -1로 기록되고 있었습니다.

Add missing non native chain infos in register enable chains to amplitude logging

---

packages/background/src/chains/service.ts
packages/background/src/keyring-ethereum/service.ts

이더민트 계열의 체인이 `currentChainId`가 되면 chain id를 파싱이 필요한 JSON RPC 요청에서 오류가 남
-> chain id를 직접 파싱하지 않고 chainInfo를 조회하여 `chainInfo.evm.chainId`를 반환하도록 수정

Fix an issue that parsing ethermint chain id on background

---

apps/extension/src/pages/earn/components/overview-claim-section.tsx

이벤트 이름이 정의되지 않았어서 `noble_earn_claim_yield`라는 모호한 이름으로 기록되고 있었습니다.
새로 정의한 이름으로 기록하고, amplitude의 transform -> merge duplicate 기능 이용하여 합치려고 합니다.

Rename approve claim tx amplitude event in earn overview page

---

packages/chain-validator/src/feature.ts
packages/stores/src/account/cosmos.ts

Adds Cosmos EVM pubkey support using the new `/cosmos.evm.crypto.v1.ethsecp256k1.PubKey` pubkey.
Proto ref: https://github.com/cosmos/evm/blob/26aa83df0c62e0bd70cef66331430c5a8ba4cf9a/proto/cosmos/evm/crypto/v1/ethsecp256k1/keys.proto#L12

Add cosmos-evm pubkey and feature

---

apps/extension/src/pages/permission/basic-access-for-bitcoin/index.tsx
packages/background/src/permission/service.ts

`baseChainId` 가 chain id가 아닌 chain identifier라서 이더민트 계열의 체인의 경우 퍼미션 추가하는 UI에 드롭다운에서 기본 선택이 안되는 문제
-> UI에선 chain identifier가 아닌 chainId를 다루도록 변경

Fix an issue that use chain identifier on permission ui

---

packages/background/src/keyring-ethereum/service.ts

- `authorizationList`가 파라미터에 들어있으면 7702 트랜잭션이라고 간주하고 오류를 반환하도록 추가했습니다.

Reject EIP-7702 tx request

---

apps/extension/src/pages/main/components/claim-all/index.tsx
apps/extension/src/stores/huge-queries/index.ts

현재 EVM RPC에도 Cosmos delegations, undelegations, rewards 쿼리하고 있음
-> 쿼리하지 않도록 수정

Prevent cosmos queries from being sent through EVM RPC

---

packages/background/package.json
yarn.lock

최신 버전(2.3.1)의 Starknet Ledger app을 사용하는 유저는 케플러로 Starknet 트랜잭션 서명이 불가한 이슈
-> 케플러에서 사용하는 Starknet Ledger JS 라이브러리 버전을 최신으로 변경해서 해결

Upgrade Starknet Ledger JS library version

---

packages/stores/src/account/base.ts

- 익스텐션에서는 enable chains 페이지가 새로운 웹페이지에서 열리므로 콘텍스트가 달라져서 새로 getKey 요청이 들어가기 때문에 문제가 없지만, 
- 모바일은 동일한 콘텍스트에서 enable chains 페이지가 열리므로 캐시된 키를 사용
- 따라서 비트코인 키 정보가 존재하지 않거나 다른 유형의 키인 경우 undefined 처리를 하도록 추가했습니다.

Resolve other account's bitcoin address are cached on mobile

---

packages/hooks-starknet/src/tx/amount.ts
packages/hooks-starknet/src/tx/chain.ts
packages/hooks-starknet/src/tx/name-service-starknet-id.ts
packages/hooks-starknet/src/tx/noop-amount.ts
packages/hooks-starknet/src/tx/recipient.ts
packages/hooks-starknet/src/tx/types.ts

- `hooks-starknet`의 ModularChainInfo 사용을 IModularChainInfoImpl로 변경

Fix starknet amount config cannot identify custom tokens

---

apps/extension/src/pages/main/components/deposit-modal/qr-code.tsx
apps/extension/src/pages/main/token-detail/receive-modal/index.tsx

QR 코드 인식률이 떨어져서, 생성 시 이미지 내 로고 사이즈를 줄입니다.

Resize Keplr logo in QR code

---

apps/extension/src/pages/ibc-swap/select-asset/index.tsx

- coinMinimalDenom은 동일하지만, 사용가능한 자산과 불가능한 자산을 엄격하게 분리할 필요가 있어 개별 자산에 대한 탐색만을 실행하도록 수정했습니다.

Use chain-specific keys for unsupported and finding states in IBC Swap asset selection

---

apps/extension/src/analytics-amplitude.ts
apps/extension/src/pages/ibc-swap/hooks/use-swap-analytics.ts

- 이번 변경으로 인해 `swap_entry` 이벤트의 `wallet_type` property가 redundant 해졌으므로 제거

Add current_keyring_type as Amplitude User Property

---

apps/extension/src/stores/root.tsx
packages/background/src/chains-ui/foreground/constants.ts
packages/background/src/chains-ui/foreground/handler.ts
packages/background/src/chains-ui/foreground/index.ts
packages/background/src/chains-ui/foreground/init.ts
packages/background/src/chains-ui/foreground/messages.ts
packages/background/src/chains-ui/foreground/service.ts
packages/background/src/chains/service.ts
packages/background/src/index.ts
packages/background/src/keyring/service.ts
packages/background/src/token-scan/service.ts
packages/stores-core/src/core/chains-ui/index.ts
packages/stores-core/src/core/index.ts

- background의 token scan service에서 suggest chain 이후 token scan이 완료되면 자동으로 token scan에서 결과가 하나인 경우 (바로 enable 해줘도 문제 없는 경우) 자동으로 enable 하도록 수정
- background에서 자동으로 enable될때 UI가 켜져있으면 자동으로 sync해주기 위해서 ChainsUIForeground 추가
- bitcoin같이 여러 체인이 하나로 붙어있는(?) 경우를 처리하기 위해서 ChainsService에 getModularChainInfoWithLinkedChainKey()라는 메소드 추가 -> 해당하는 체인에 linkedChainKey가 있을 경우 같은 linkedChainKey를 가진 modularChainInfo를 같이 반환

논네이티브 체인 추가되는 시점에 해당 체인에 자산이 있는 경우 체인 활성화

---

apps/extension/src/config.ts

- unichain도 op stack으로 처리되도록 피쳐 추가
- 참조: https://github.com/ethereum-optimism/superchain-registry/blob/main/CHAINS.md

Unichain missing `op-stack-l1-data-fee` feature

---

apps/extension/package.json
apps/extension/src/pages/sign/utils/handle-starknet-sign.ts
yarn.lock

- 여러 개의 콜데이터가 들어있는 트랜잭션을 실행할 때, (ex. swap on [ekubo](https://app.ekubo.org/?inputCurrency=STRK&amount=0.1&outputCurrency=EKUBO))
- 콜데이터를 파싱하는 과정에서 로우 레벨에서 렛져로 2개 이상의 요청이 거의 동시에 들어가고 순차적으로 처리되지 않는 문제가 발생
- error: `An action was already pending on the Ledger device. Please deny or reconnect.`
- ledger nano s+ 및 stax 모두 동일한 오류 발생
- ledger(transport) 및 starknet 라이브러리 버전을 최신으로 올려서 테스트 해봐도 동일한 문제가 발생해서 라이브러리 문제인지는 판별이 어렵습니다
- 임시방편으로 로우 레벨 요청을 수행하는 메서드의 요청을 가로채서 요청 큐에 넣어 순차적으로 실행하도록 구현

Handle ledger low level request in order on starknet ledger app

---

packages/hooks/src/tx/fee.ts
packages/stores-eth/src/queries/fee-histroy.ts

- https://github.com/chainapsis/keplr-wallet/pull/1559
- arbitrum 등 priority를 지원하지 않는 체인이 존재하므로 0보다 크다는 조건 검사 제거
- fee history 또는 max priority fee를 가져오지 못하는 경우에 대한 ui에서의 에러 처리가 충분하므로 default max priority(1.5 gwei)를 제거하고 0을 반환하도록 수정

Calculate maxPriorityFeePerGas based on latest fee history v2

---

packages/background/src/secret-wasm/enigma-utils.ts

This commit removes hard-coded mainnetConsensusIoPubKey for SecretNetwork to avoid manually changing it after each network seed rotation. The key will now be fetched during the first call to getConsensusIoPubKey() function.

Remove hard-coded consensusIoPubKey for SecretNetwork

---

apps/extension/src/pages/manage-chains/index.tsx

- 필터가 All일 때 전체 체인 리스트가 보여야 하므로 불필요한 `preSortGroupedModularChainInfos` 제거
- 렛저 계정일 때,  이더민트 계열 체인인지 우선 확인하도록 수정
- 렛저 계정일 때, 이더민트 계열 체인은 Evm으로 필터링되도록 수정

Fix displaying ledger chain list on manage chains page
