chainapsis/keplr-wallet

- src/config.ts
- src/ui/popup/pages/send/index.tsx
- Added Tamagotchi endpoints (two chains, one channel, 6 currencies)
- Fixed validation for "IBC send" form when gas denom is different from sending denom
> Add Tamagotchi endpoints and fix ibc send form validation

- package-lock.json
- package.json
- src/content-scripts/inject/common.ts
- src/content-scripts/inject/cosmjs-offline-signer.ts
- src/content-scripts/inject/injected-script.ts
- src/window.d.ts
Add `window.getOfflineSigner(chainId:string)` method that will be injected to webpage based on `@cosmjs/launchpad@0.23.0-alpha.0`.
Here is an example of how to use the current version. https://github.com/chainapsis/keplr-example/blob/comsjs/src/main.js
> Cosmjs launchpad `offlineSigner` implementation

- package.json
> modify order lerna clean

- packages/background/src/keyring/handler.ts
- packages/background/src/keyring/init.ts
- packages/background/src/keyring/keyring.ts
- packages/background/src/keyring/messages.ts
- packages/background/src/keyring/service.ts
- packages/extension/src/index.tsx
- packages/extension/src/languages/en.json
- packages/extension/src/languages/ko.json
- packages/extension/src/pages/setting/keyring/change/index.tsx
- packages/extension/src/pages/setting/keyring/change/name.module.scss
- packages/extension/src/pages/setting/keyring/change/name.tsx
- packages/extension/src/pages/setting/keyring/index.tsx
- packages/stores/src/core/keyring.ts
> feat : update account name

- docs/api/suggest-chain.md
Add more details for suggest chains documentation
> Add more details for suggest chains documentation

- packages/extension/src/config.var.example.ts
> Add networks config example

- docs/api/README.md
Good ol' documentation fixes, amiright
> change DirectOfflineSigner » OfflineDirectSigner

- docs/api/README.md
mostly language but one bug fix with window.keplr
> Some docs changes

- packages/background/src/chains/types.spec.ts
- packages/background/src/chains/types.ts
- packages/background/src/tokens/service.ts
- fix typo `Shema` -> `Schema`
- add test for Secret20Currency
> Add test for Secret20Currency token

- packages/extension/src/pages/main/account.tsx
- packages/stores/package.json
- packages/stores/src/account/base.ts
> Add hex UI to account page when on Evmos Chain

- packages/extension/src/pages/register/style.module.scss
| Before | After |
|:---:|:---:|
| <img width="520" alt="스크린샷 2022-04-26 오후 11 38 44" src="https://user-images.githubusercontent.com/32605822/165330256-34e275f4-fa13-45ce-bbfd-2e48ec6f0203.png"> | <img width="519" alt="스크린샷 2022-04-26 오후 11 52 16" src="https://user-images.githubusercontent.com/32605822/165330277-668fa291-c2fd-4ba0-8361-9893e1e51861.png"> |
> Normalize font-family of mnemonic input placeholder

- packages/mobile/src/config.ts
Update mobile config for current chain-id
> update Secret Network chain-id

- packages/extension/src/config.ts
- packages/mobile/src/config.ts
Renames RUN to IST - i *think* this is ok with the wallet secrets injection, but I'm unsure if more needs to be changed for that to be happy
fixes: #446
> fix: rename RUN to IST for the agoric chain

- packages/background/src/keyring/keyring.ts
- packages/background/src/keyring/service.ts
> Remove all keyring's coin type whenever chain removed

- packages/stores/src/query/cosmos/supply/inflation.ts
> Fix Umee APR incorrect

- packages/background/src/updater/service.ts
- packages/chain-validator/src/feature.spec.ts
- packages/chain-validator/src/feature.ts
- packages/chain-validator/src/index.ts
Detailed logic was extracted as a "checkChainFeatures" function.
> Fix checkChainUpdate logic(Add checkChainFeatures in chain-validator)

- packages/extension/src/config.ts
- packages/mobile/src/config.ts
Updates the fees to accommodate the minfee of 0.0036BLD (3600ubld)
> fix: adjust fees and add BLD

- packages/crypto/package.json
- packages/crypto/src/hash.spec.ts
- packages/crypto/src/hash.ts
- packages/crypto/src/key.spec.ts
- packages/crypto/src/key.ts
uncompressed pubkey -> remove  prefix byte -> keccak256 -> use last 20 bytes
Add a method to create an ethereum address in the above way.
Haven't actually used it yet.
> Add `getEthAddress()` method to pub key

- packages/extension/src/config.ts
`https://wallet.keplr.app/chains/certik` => `https://wallet.keplr.app/chains/shentu`
> Update `shentu` chain dashboard URL

- packages/stores/src/price/index.ts
Fixes https://github.com/chainapsis/keplr-wallet/issues/607
Closed #608 to do development with `develop` branch vs `master`.
> Short circuit price calculation if amount is 0

- packages/extension/src/pages/keystone/scan.tsx
Fix:
When error message is showing, scanner is still working.
> fix error msg when scan

- packages/extension/src/stores/chain/index.tsx
- Change disabled chain value from chain id to chain id identifier
- Change last view chain id save logic from PersistentMemory to KvStore
> Fix chain store logics

- packages/extension/src/components/collapse/index.tsx
- packages/extension/src/components/collapse/style.module.scss
- packages/extension/src/index.tsx
- packages/extension/src/languages/en.json
- packages/extension/src/languages/ko.json
- packages/extension/src/pages/authz/index.tsx
- packages/extension/src/pages/authz/style.module.scss
- packages/extension/src/pages/main/authz.module.scss
- packages/extension/src/pages/main/authz.tsx
- packages/extension/src/pages/main/index.tsx
- packages/stores/src/account/cosmos.ts
- packages/stores/src/query/cosmos/authz/index.ts
- packages/stores/src/query/cosmos/authz/types.ts
- packages/stores/src/query/cosmos/index.ts
- packages/stores/src/query/cosmos/queries.ts
- Add authz granter query view.
- Add authz detail page.
- Add authz revoke message.
> [Extension] Add authz view

- packages/extension/src/languages/en.json
- packages/extension/src/languages/ko.json
- packages/extension/src/layouts/header/chain-list.tsx
> [Extension] Fix suggest chain link title

- docs/api/README.md
- docs/api/cosmjs.md
> Fix: typos

- packages/extension/src/hooks/use-buy.ts
According to this [doc](https://docs.transak.com/docs/query-parameters) It doesn't need a signature anymore
> Remove moonpay url signature

- packages/mobile/src/components/input/fee-buttons.tsx
- packages/mobile/src/components/input/fee-selector.tsx
- packages/mobile/src/components/input/index.ts
- packages/mobile/src/config.ts
- packages/mobile/src/modals/sign/fee.tsx
- packages/mobile/src/screens/send/index.tsx
- packages/mobile/src/stores/root.tsx
> [Mobile] Add multi fee selector

- packages/extension/src/pages/main/asset.tsx
> [Extension] Fix noble asset view

- packages/background/src/analytics/handler.ts
- packages/background/src/analytics/init.ts
- packages/background/src/analytics/messages.ts
- packages/background/src/analytics/service.ts
- packages/extension/src/pages/setting/security/index.tsx
- packages/extension/src/stores/root.tsx
Added an analytics setting under Privacy in Settings.
> Add analytics setting option

- packages/extension/src/pages/setting/security/index.tsx
- Add `disableAnalytics` state
- Remove `window.location.reload()`
> Fix analytics setting logic

- packages/extension/src/stores/root.tsx
Improves the gas estimation on send messages, as we're facing the same issue Evmos had in the beginning with Keplr gas estimation.
> Fix planq gas usage

- packages/extension/src/pages/register/enable-chains/index.tsx
- except Ledger EVM select page
> Add select all logic on `enable-chains` page

- packages/unit/src/coin-pretty.ts
- packages/unit/src/price-pretty.spec.ts
- packages/unit/src/price-pretty.ts
- packages/unit/src/rate-pretty.ts
In the original logic, operations only change the intPretty value, so i modified it to change the amount as well
The amountToString() method was added for testing
> fix: add amount logic in operation

- packages/extension/src/components/guide-box/styles.ts
- packages/extension/src/pages/main/components/token-found-modal/index.tsx
- packages/extension/src/pages/register/components/form/name-password.tsx
- packages/extension/src/pages/register/name-password-hardware/index.tsx
- packages/extension/src/pages/register/name-password/index.tsx
- packages/extension/src/pages/register/verify-mnemonic/verifying-box.tsx
- [Add auto focus in register page](https://github.com/chainapsis/keplr-wallet/commit/fa907bd1f6eb9e806503918f691915e3916031d8)
- [Fix token found modal text size](https://github.com/chainapsis/keplr-wallet/commit/10dcc074674ee3dc79b3e6eb53cdcc9db9b8bef7)
- [Fix danger guide box color](https://github.com/chainapsis/keplr-wallet/commit/6eefaaaf8ce031ef1891650f9b733337e083b9ab)
> Fix minor UI

- packages/extension/src/languages/en.json
- packages/extension/src/languages/ko.json
- packages/extension/src/ledger-grant.tsx
- packages/extension/src/pages/setting/general/authz/revoke/index.tsx
- Fix Typo
- Add intl on ledger grant page
- Add copy to clipboard on AuthZ revoke page
> Fix minimum things

- packages/background/src/keyring-ledger/service.ts
- packages/extension/src/pages/register/connect-ledger/index.tsx
- packages/extension/src/pages/register/name-password-hardware/index.tsx
- packages/extension/src/pages/wallet/select/index.tsx
- packages/ledger-cosmos/src/app.ts
- packages/ledger-cosmos/src/types.ts
Support the 529 coin type derivation path when importing a Ledger account with the Secret app
> 529 Coin-type Supporting

- packages/mobile/src/modals/sign/adr36.tsx
- packages/mobile/src/providers/interaction-modals-provider/index.tsx
- packages/mobile/src/stores/wallet-connect-v2/index.ts
- packages/mobile/src/stores/wallet-connect-v2/schema.ts
> Add signArbitrary using WC2

- packages/mobile/android/app/src/main/AndroidManifest.xml
- packages/mobile/android/build.gradle
- packages/mobile/package.json
- yarn.lock
- Changing location-related permissions
- https://developer.android.com/training/location/permissions?hl=ko#approximate-request
- Fix webview library version
- https://github.com/react-native-webview/react-native-webview/issues/2547
> Fix permission for Android SDK v33

- packages/mobile/App.tsx
- packages/mobile/src/components/modal/modal.tsx
backdrop 위치가 헤더를 가리지 않아서  provdier위치를 네이게이션을 포함 할 수있게 변경했습니다
> Fix: move bottom sheet provider

- packages/mobile/src/components/checkbox/checkbox.tsx
- packages/mobile/src/components/collapsible-list/collapsible-list.tsx
- packages/mobile/src/components/collapsible-list/index.ts
- packages/mobile/src/components/collapsible-list/types.ts
- packages/mobile/src/components/empty-view/index.tsx
- packages/mobile/src/components/icon/arrow-down.tsx
- packages/mobile/src/components/icon/arrow-right.tsx
- packages/mobile/src/components/icon/arrow-up.tsx
- packages/mobile/src/components/input/search-text-input/index.tsx
- packages/mobile/src/components/tag/index.tsx
- packages/mobile/src/screen/home/available.tsx
- packages/mobile/src/screen/home/components/empty-view/index.tsx
- packages/mobile/src/screen/home/components/looking-for-chains/index.tsx
- packages/mobile/src/screen/home/components/token-found-modal/index.tsx
- packages/mobile/src/screen/home/components/token/index.tsx
- packages/mobile/src/screen/home/index.tsx
- packages/mobile/src/styles/index.tsx
아직 tooltip 이랑 패스트 이미지는 구현이 안되어있습니다 이후 구현해서 적용해야 됩니다.
checkbox컴포넌트를 좀 건들였는데요 mobile-2에서 브랜치 따서 머지하기에는 시간이 좀 많이 걸릴것 같아서 일단 해당 브랜치에서 같이 작업했습니다. 이유는 checkbox의  onPress에서 받아오는 이벤트가 웹이랑 따로 커스텀해서 만들었다 보니 check에 대한값을 넘겨주지 않아서 일단 같이 넘겨주는 방식으로 변경 했습니다. 
주석처리된 부분은 나중에 적용해야 될 점으로 혹시나 까먹을까봐 일단 유지를 위해서 주석 처리를 했습니다.
> [KM-17] available tab 구현

- packages/mobile/ios/Podfile.lock
- packages/mobile/src/components/axis/y.tsx
- packages/mobile/src/components/box/box.tsx
- packages/mobile/src/components/box/types.ts
- packages/mobile/src/components/button/button.tsx
- packages/mobile/src/components/collapsible-list/collapsible-list.tsx
- packages/mobile/src/components/empty-view/index.tsx
- packages/mobile/src/components/icon-button/icon-button.tsx
- packages/mobile/src/components/image/index.tsx
- packages/mobile/src/components/input/text-input/text-input.tsx
- packages/mobile/src/components/mnemonic-input/mnemonic-input.tsx
- packages/mobile/src/components/modal/modal.tsx
- packages/mobile/src/components/page/scroll-view.tsx
- packages/mobile/src/components/pageHeader/header.tsx
- packages/mobile/src/components/text-button/text-button.tsx
- packages/mobile/src/screen/home/available.tsx
- packages/mobile/src/screen/home/buy-modal.tsx
- packages/mobile/src/screen/home/deposit-modal.tsx
- packages/mobile/src/screen/locked/index.tsx
[ticket](https://linear.app/chainapsis/issue/KM-32/fastimage-%EC%99%80-box%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EB%A1%9C-%EA%B5%90%EC%B2%B4-%EC%9E%91%EC%97%85)
view 를 box로 교체
image 컴포넌트를  fast image 컴포넌트로 교체
> [KM-32] box, fast image 컴포넌트 교체 작업

- packages/mobile/src/screens/setting/screens/connections/index.tsx
PR to fix text overflow in issue #850
> Minor fix for #850 text overflow issue

- packages/mobile/App.tsx
- packages/mobile/src/screen/send/select-asset/index.tsx
뷰 그리는데 성능이슈가 있어 PageWithScrollView에서 FlatList로 변경하였습니다.
@blacktoast
> Fix select asset page style to flat list

- packages/mobile/src/screens/web/index.tsx
> Remove favorite collapse

- packages/mobile/src/components/input/text-input/text-input.tsx
- packages/mobile/src/components/mnemonic-input/mnemonic-input.tsx
> Fix mobile 2.0 type check

- packages/mobile/src/components/page/background.tsx
- packages/mobile/src/styles/index.tsx
기존 디자인에 맞춰서 컬러 팔레트를 업데이트 했습니다
`'background-tertiary'` 컬러는 더이상 사용되지 않는다고 해서 삭제했습니다
@HeesungB
> Update color pallet

- packages/mobile/src/styles/index.tsx
디자인대로 text color를 추가했습니다
@HeesungB
> text color 추가

- package.json
CI에서 테스트 코드가 깨져서 순서를 수정했습니다.
@blacktoast 다른 브랜치에서 할 때 이거먼저 rebase해서 사용해주세요
> Fix test sequence

- packages/mobile/src/components/address-item/index.tsx
- packages/mobile/src/components/box/box.tsx
- packages/mobile/src/components/box/types.ts
- packages/mobile/src/components/dropdown/index.tsx
- packages/mobile/src/components/input/fee-control/fee-selector.tsx
- packages/mobile/src/components/toggle/index.tsx
- packages/mobile/src/screen/wallet/select/index.tsx
박스에서 onClick이 있으면 Pressable하게 만들었습니다.
> [KM-39] Fix box as pressable

- packages/mobile/src/components/box/box.tsx
Remove nested view, fix as one view
> Fix Pressable box

- packages/mobile/src/components/toggle/index.tsx
Add small size toggle component
> Add toggle small size

- packages/mobile/src/components/dropdown/index.tsx
- packages/mobile/src/components/input/fee-control/transaction-fee-modal.tsx
- packages/mobile/src/screen/send/amount/index.tsx
- dropdown 컴포넌트의 zindex 문제를 해결하였습니다.
- send 페이지에서 구현되지 않은 기능을 추가하였습니다.
- Fixed a zindex issue with the dropdown component.
- Added unimplemented functionality on the send page.
> [KM-54] Dropdown component

- packages/mobile/src/modals/sign/agoric/msg-wallet-spend-action.tsx
- packages/mobile/src/screens/web/components/webpage-screen/index.tsx
- Make the fonts look more similar to other messages.
- Allow wallet.agoric.app to suggest chains, for easier testing with Agoric testnets.
> Improve agoric message styling

- packages/mobile/src/components/drawer/index.tsx
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/home/available.tsx
- packages/mobile/src/screen/home/components/token/index.tsx
- packages/mobile/src/screen/setting/screens/general/general.tsx
- packages/mobile/src/screen/setting/screens/token/add/index.tsx
- packages/mobile/src/screen/wallet/delete/index.tsx
메인 사이드바에서 add token과  contacts를 클릭 했을때 해당 페이지로 이동 하는 라우트 추가
delete wallet시 더이상 keyring이 없으면 registre 페이지로 이동
> [Feat] 메인 사이드바 route와 delete wallet 버그 수정

- packages/mobile/src/screen/home/components/stakeing-chain-select-modal/index.tsx
- packages/mobile/src/screen/home/components/token/index.tsx
- packages/mobile/src/screen/home/staked.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/stores/aprs/index.ts
클릭 가능한 아이템에 오른쪽 화살표를 추가 했습니다
token item을 수정해서 apr을 가져올때 `apr - %` 형태로 보여주게 했습니다
> 클리가능한 요소 arrow 추가

- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/register/components/bip-path-44/hook.ts
- packages/mobile/src/screen/register/components/bip-path-44/index.ts
- packages/mobile/src/screen/register/components/bip-path-44/modal.tsx
- packages/mobile/src/screen/register/components/bip-path-44/state.ts
- packages/mobile/src/screen/register/components/register-container.tsx
- packages/mobile/src/screen/register/new-mnemonic/index.tsx
- packages/mobile/src/screen/register/verify-mnemonic/index.tsx
- confirm 모달은 현재 타이밍이 애매해서 빼놨습니다. 모바일 회의 때 얘기해서 조정할 예정입니다.
> [KM-64] Add verify mnemonic screen

- packages/mobile/src/components/drawer/index.tsx
- packages/mobile/src/components/pageHeader/header-register.tsx
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/register/enable-chains/index.tsx
- packages/mobile/src/screen/register/finalize-key/index.tsx
- packages/mobile/src/screen/register/intro-new-user/index.tsx
- packages/mobile/src/screen/register/intro/index.tsx
- packages/mobile/src/screen/register/new-mnemonic/index.tsx
- packages/mobile/src/screen/register/verify-mnemonic/index.tsx
- enable chains 페이지를 추가하였습니다. -> 최초 회원가입, 홈에서도 접근 가능
- 계정의 비밀번호를 지정하면 다시 지정 안해도 되게 로직을 추가하였습니다.
> [KM-64] Add Enable chains screen

- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/home/staked.tsx
줄리님이랑 이야기해서 stack dashboard route를 기존대로 롤백했습니다
다른 기능 구현뒤 나중에 다시 작업하기로 했습니다
> Fix drawer

- packages/mobile/src/components/icon/arrow-down-up.tsx
- packages/mobile/src/components/icon/index.ts
- packages/mobile/src/components/input/search-text-input/index.tsx
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/home/staked.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/dashboard/dashboard.tsx
- packages/mobile/src/screen/staking/type.ts
- packages/mobile/src/screen/staking/validator-list/index.tsx
- packages/mobile/src/screen/staking/vlidator-list/index.tsx
validator list 구현
voting power에서 comisson으로 바뀌는 부분은 나중에 모달로 변경예정입니다
> [KM-66] vadlidator list page 구현

- packages/mobile/src/components/progress-bar/index.tsx
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/staking/components/validator-image/index.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/dashboard/dashboard.tsx
- packages/mobile/src/screen/staking/validator-detail/delegated-card.tsx
- packages/mobile/src/screen/staking/validator-detail/index.tsx
- packages/mobile/src/screen/staking/validator-detail/unbonding-card.tsx
- packages/mobile/src/screen/staking/validator-list/index.tsx
- packages/mobile/src/styles/index.tsx
> [KM-66] validator detail 페이지 구현

- packages/mobile/src/screen/register/components/register-container.tsx
- packages/mobile/src/screen/register/enable-chains/index.tsx
- packages/mobile/src/screen/register/select-derivation-path/index.tsx
- 실제 디바이스에서 Keyboard가 올라왔을 때 뷰가 잘 안보이는 부분을 수정하였습니다.
> Add KeyboardAvoidingView on register screens

- packages/mobile/src/screen/staking/components/validator-image/index.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/validator-list/index.tsx
1. 벨리데이터 리스트 성능 향상을 위해서
벨리데이터 아이템에서 지속적으로 비교하서 만드는 substring 값을 ref로 캐싱하였고
isDelegtion값을 부모 컴포넌트에서 내릴수 있도록 변경했습니다
2. fastImage에 1.0 처럼 캐싱 옵션을 추가 했습니다
3. 현재 validator list에서 스크롤을 빠르게 올릴시 중간에 빈공간을 볼수 있는데 해당 부분을 막기 위해서 windowSize를 조정 했습니다
해당 옵션은 올릴수록 메모리를 많이 먹는다고 해서 그렇게 빨리 스크롤을 빨리 올릴 유저가 없다면 빼도 될것 같습니다
https://reactnative.dev/docs/optimizing-flatlist-configuration
> Optmize validator list

- packages/mobile/src/screen/web/webpage.tsx
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#applicationnameforuseragent
> [KM-87] Add user agent on webpage screen

- packages/mobile/src/screen/home/buy-modal.tsx
- packages/mobile/src/screen/home/index.tsx
기존 buymodal에서 클릭시 webView로 라우팅 될수있게 수정
> [KM-29] buy modal 웹뷰로 라우팅

- packages/background/src/secret-wasm/service.ts
> Fix: getSeedInner with Keystone

- packages/mobile/App.tsx
- packages/mobile/src/components/transition/vertical-collapse/collapse.tsx
- packages/mobile/src/hooks/notification/index.ts
- packages/mobile/src/hooks/notification/internal/context.tsx
- packages/mobile/src/hooks/notification/internal/index.tsx
- packages/mobile/src/hooks/notification/internal/provider.tsx
- packages/mobile/src/hooks/notification/types.ts
- packages/mobile/src/screen/send/amount/index.tsx
- packages/mobile/src/screen/staking/delegate/index.tsx
- packages/mobile/src/screen/staking/redelegate/index.tsx
- packages/mobile/src/screen/staking/undelegate/index.tsx
트랜잭션 이후 성공 및 실패시 토스트를 보여줍니다
- 재pr 합니다
> [KM-83] toast 추가

- packages/mobile/ios/Podfile.lock
- packages/mobile/src/components/modal/hooks/useBottomSheetBackHandler.tsx
- packages/mobile/src/components/modal/modal.tsx
#구현사항
안드로이드에서 백버튼 클릭시 modal이 닫히게 구현 했습니다
https://github.com/gorhom/react-native-bottom-sheet/issues/1110#issuecomment-1352865270 참조
> [KM-95] android 에서 백버튼 클릭시 모달 닫기

- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/setting/screens/general/general.tsx
- packages/mobile/src/screen/setting/screens/general/version/index.tsx
- packages/mobile/src/styles/index.tsx
케플러 버전 페이지 구현
주석처리된 코드들은 코드푸쉬에 이후 해당 버전올 보여줘야 하기때문에
코드푸쉬 적용 이후 다시 넣을 예정입니다
> [KM-96] keplr version 페이지 추가

- packages/mobile/src/components/modal/global-permission.tsx
- packages/mobile/src/components/modal/index.ts
- packages/mobile/src/components/modal/suggest-chain.tsx
- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/provider/interaction-modals-provider/index.tsx
- Permission Global Modal을 추가하였습니다. [스크린샷 1]
- Suggest Chain Community Modal 디자인 추가 [스크린샷 2]
- Suggest Chain Raw Modal 디자인 추가 [스크린샷 3]
> [KM-80] Fix suggest chain design

- packages/mobile/src/provider/interaction-modals-provider/index.tsx
- packages/mobile/src/screen/sign/sign-adr36-modal.tsx
- ADR36 Sign Modal을 추가하였습니다.
- wallet.keplr.app에서 프로필 사진 바꾸는 걸로 테스트 가능합니다.
> [KM-98] Add sign ADR36 modal

- packages/mobile/src/components/modal/basic-access.tsx
> [KM-100] Fix basic access modal design

- packages/mobile/src/components/skeleton/index.tsx
- packages/mobile/src/screen/home/available.tsx
- packages/mobile/src/screen/send/amount/index.tsx
- packages/mobile/src/screen/send/select-asset/index.tsx
ce3416a277be4dcccfb76c36840731c420e9f1bf 
-> send페이지에서 네이게이션이 여러개 쌓였을때 뒤로가기시 send페이지가 보여질수 있게 수정
1ef7b4ac978daf57ca94439c7cfe76a62c5ddd17
-> 안드로이드에서 스켈레톤이 보여줄 수 있게 수정
7b55552496a323fb3aa4661f0f7302b1ef63f790
-> main에서 empty view 텍스트 컬러 수정
> [KM-99, 104] send네이게이션, 스켈레톤 및 기타 수정

- packages/mobile/src/components/dropdown/index.tsx
- packages/mobile/src/components/input/fee-control/fee-selector.tsx
- packages/mobile/src/components/input/fee-control/index.tsx
- packages/mobile/src/components/input/fee-control/transaction-fee-modal.tsx
- Transaction Fee 디자인 적용하였습니다
https://www.notion.so/chainapsis/Transaction-Fee-88fc7978fc0e4498a26e30ffdd46d08c?pvs=4
- Fee option Low, Average, High로 수정하였습니다.
https://www.notion.so/chainapsis/Fee-Option-Low-Average-High-Low-Average-Low-69d1fa6e1bbf440d98890315537d172e?pvs=4
- BottomSheetModal -> Modal V2로 변경하였습니다.
- DropDown 외부에서 스타일 받을 수 있게 변경하였습니다.
> [KM-79] Fix fee control in sign modal

- packages/mobile/src/screen/register/components/bip-path-44/index.ts
- packages/mobile/src/screen/register/components/bip-path-44/view.tsx
- packages/mobile/src/screen/register/connect-hardware/index.tsx
- packages/mobile/src/screen/register/recover-mnemonic/index.tsx
- packages/mobile/src/screen/register/verify-mnemonic/index.tsx
- packages/mobile/src/styles/index.tsx
> [KM-76] Fix BIPpath style

- packages/mobile/src/components/modal/infoModal.tsx
- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/home/available.tsx
- packages/mobile/src/screen/home/components/token/index.tsx
- packages/mobile/src/screen/home/staked.tsx
1. infomodal v2 모달로 수정
2. infomoal 하단에 버튼 주입 받을 수 있게 수정
> [KM-102] 에러 모달 추가

- packages/mobile/src/components/guide-box/guide-box.tsx
- packages/mobile/src/components/guide-box/types.ts
- packages/mobile/src/components/input/fee-control/index.tsx
> [KM-105] Add error status on fee control

- packages/mobile/src/components/drawer/index.tsx
- packages/mobile/src/components/pageHeader/header.tsx
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/register/enable-chains/index.tsx
- packages/mobile/src/screen/setting/screens/general/general.tsx
메인으로 부터 enable체인 페이지에 들어왔을때 뒤로가기 버튼 보일수 있게 수정
qa에 맞춰서 패딩값 수정 :  03808590b53e10e80c769ea56de3328e192f98ce
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=e113d994d19e4b60885c531b2c91fb57&pm=s
> [QA] enable chain qa 적용

- packages/mobile/src/components/radio-group/layered/layered.tsx
- packages/mobile/src/screen/home/index.tsx
메인 페이지에서 스켈레톤을 추가 했습니다
현재 radio 그룹에서 스켈레톤시 중첩된 원 없이 원이 하나만 보이는데 
nested 뷰에서 zindex가 적용이 안되고 있어서 일단 그외 스켈레톤이라도 추가하려고 PR을 했습니다
> [KM-106] 메인 페이지에서 스켈레톤 추가

- packages/mobile/src/components/pageHeader/header-register.tsx
- packages/mobile/src/components/pageHeader/header.tsx
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/register/components/register-container.tsx
- packages/mobile/src/screen/register/connect-hardware/index.tsx
- packages/mobile/src/screen/register/connect-ledger/index.tsx
- packages/mobile/src/screen/register/enable-chains/index.tsx
- packages/mobile/src/screen/register/intro-existing-user/index.tsx
- packages/mobile/src/screen/register/intro-new-user/index.tsx
- packages/mobile/src/screen/register/new-mnemonic/index.tsx
- packages/mobile/src/screen/register/recover-mnemonic/index.tsx
- packages/mobile/src/screen/register/select-derivation-path/index.tsx
- packages/mobile/src/screen/register/verify-mnemonic/index.tsx
전체 헤더 높이를 맞추기 위해서 커스텀 헤더를 일반 헤더로 교체 했습니다
> [KM-107] 커스텀 헤더 -> 일반 헤더로 교체 작업

- packages/mobile/src/components/select-modal/index.tsx
- packages/mobile/src/screen/governance/components/select-modal-gov/index.tsx
- packages/mobile/src/screen/governance/index.tsx
- packages/mobile/src/screen/setting/components/contract-address-book-modal/index.tsx
- packages/mobile/src/screen/setting/screens/contacts/list/index.tsx
- packages/mobile/src/screen/setting/screens/token/add/index.tsx
- packages/mobile/src/screen/setting/screens/token/manage/index.tsx
- packages/mobile/src/screen/staking/dashboard/dashboard.tsx
708ff34fda2fa36ed607ecb70f91814a16571ffc
-> token add,list 페이지의 select chain 모달 변경 
1a1b997c07d535a7430e129ff754a389b55fc674
-> add token 페이지의 contract 모달 변경
9b0240894d1edc8ce1581c179b792a175f414951
-> contacts 페이지의 select chain 모달 변경
7d2fc93a44796e2f80593aec10951c8291f70b25
-> 투표할 프로포절이 있는 페이지에서 체인 선택 모달 변경
> [KM-111] 기존 모달을 v2 모달로 교체 했습니다

- packages/mobile/src/components/modal/card/index.tsx
- packages/mobile/src/components/modal/menu-modal.tsx
- packages/mobile/src/screen/setting/screens/contacts/list/index.tsx
- packages/mobile/src/screen/setting/screens/token/manage/index.tsx
- packages/mobile/src/screen/wallet/select/index.tsx
> [KM-114] detached modal 추가

- packages/mobile/src/hooks/confirm/provider.tsx
- packages/mobile/src/screen/home/index.tsx
- packages/mobile/src/screen/setting/components/contract-address-book-modal/index.tsx
- packages/mobile/src/screen/setting/components/contract-item/index.tsx
90772fa11300823823a789ca601e13e7a278da5e
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=05239d6c370b4fecac2e621c4dd70c5d&pm=s : 해당 이슈 해결
54f142751f405bda94b93fa533ffa0e2e02f4233
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=f91cd66aa04948838d64261f2f91709e&pm=s : 해당 이슈 해결
92a4f608652313c1e07f3ce78cc08c8657923796
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=138242eef2ab4972800193c929d0ebe6&pm=s 해당 이슈 해결
> [QA] 디자인 qa 적용 

- packages/mobile/src/components/guide-box/guide-box.tsx
- packages/mobile/src/screen/governance/components/card.tsx
- packages/mobile/src/screen/governance/index.tsx
- packages/mobile/src/screen/governance/list/index.tsx
- packages/mobile/src/screen/home/components/claim-all/index.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/delegate/index.tsx
- packages/mobile/src/screen/staking/redelegate/index.tsx
- packages/mobile/src/screen/staking/undelegate/index.tsx
- packages/mobile/src/screen/staking/validator-detail/index.tsx
- packages/mobile/src/screen/web/webpage.tsx
- packages/mobile/src/stores/governance/v1/vote.ts
- packages/mobile/src/stores/governance/vote.ts
[cc9289d](https://github.com/chainapsis/keplr-wallet/pull/951/commits/cc9289dc9730b5f6665caa9242ff4a72b35ad6de) 
-> claim을 했을때 tx-result로 가지 않는 버그 및 토스트를 보여주지 않는 수정 : https://www.notion.so/chainapsis/Mobile-2-0-QA-Table-68368a2934ca45d7a8e113adf790f478?p=25bccd2efe9f4d4987298a4e2d57bb51&pm=s
[1835037](https://github.com/chainapsis/keplr-wallet/pull/951/commits/1835037c0e07916baaa4567cbad7942be71ad399)
-> 안드로이드에서 밸리데이터 이름이 안보이는 버그 수정 : https://www.notion.so/chainapsis/Mobile-2-0-QA-Table-68368a2934ca45d7a8e113adf790f478?p=909bd15188834e5687af1598f4668e6d&pm=s
[a829827](https://github.com/chainapsis/keplr-wallet/pull/951/commits/a829827c830f638e3610dcc9eea59067d07db021),
[d90cefa](https://github.com/chainapsis/keplr-wallet/pull/951/commits/d90cefa203c442fb004b333c5af677f30777bd25)
-> 거버넌스를 …
> [QA] 기능적 qa의 버그들 일부를 고쳤습니다

- packages/mobile/src/components/modal/index.ts
- packages/mobile/src/components/modal/need-help.tsx
- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/unlock/index.tsx
> [KM-60] Add need help modal on unlock screen

- packages/mobile/src/components/input/text-input/text-input.tsx
- packages/mobile/src/components/modal/add-token.tsx
- packages/mobile/src/components/modal/index.ts
- packages/mobile/src/provider/interaction-modals-provider/index.tsx
- text input disabled 상태일 때 텍스트 색상 변경하였습니다.
> [KM-116] Add token modal

- packages/mobile/src/components/modal/loading.tsx
- packages/mobile/src/provider/interaction-modals-provider/index.tsx
> [KM-113] Add loading modal when using deep link wallet connect

- packages/mobile/App.tsx
- packages/mobile/package.json
- yarn.lock
> [KM-122] 안드로이드에서 네비게이션 바 색상 변경

- packages/mobile/src/screen/home/available.tsx
- packages/mobile/src/screen/home/components/token-found-modal/index.tsx
https://linear.app/chainapsis/issue/KM-121/new-token-founds에서-bip-path44-선택-필요한-체인-라우팅작업
1. new token founds에서 bip path44 결정이 필요한 경우 해당 페이지로 라우팅 추가
2. 렛져일때 evmos,injective 추가할시 enable체인으로 라우팅 추가
> [KM-121] new token founds 모달에서 라우팅 추가

- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/setting/screens/contacts/add/index.tsx
- packages/mobile/src/screen/setting/screens/general/general.tsx
- packages/mobile/src/screen/setting/screens/general/wallet-connect/index.tsx
- packages/mobile/src/screen/setting/screens/security/bio-authentication/index.tsx
- packages/mobile/src/screen/setting/screens/security/change-password/index.tsx
setting페이지와 sugget chain의 text qa를 적용 했습니다
> [text-qa] settting과 suggest chain modal text qa 적용

- packages/mobile/src/components/icon/star.tsx
- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/web/index.tsx
> [text-qa] 브라우저 탭 text qa 적용

- packages/mobile/src/components/empty-view/index.tsx
- packages/mobile/src/languages/en.json
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/governance/components/select-modal-gov/index.tsx
- packages/mobile/src/screen/governance/index.tsx
- packages/mobile/src/screen/home/components/stakeing-chain-select-modal/index.tsx
- packages/mobile/src/screen/home/staked.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/delegate/index.tsx
- packages/mobile/src/screen/staking/validator-detail/index.tsx
- packages/mobile/src/screen/staking/validator-list/index.tsx
stake, 거버넌스 페이지 text qa를 반영을 진행 했습니다
거버넌스 페이지에서 디자인과 다른 부분이 있어서 여백을 추가했습니다
> [QA] stake, gov 페이지 text qa 를 진행 했습니다 

- packages/mobile/src/components/guide-box/ledger-guide-box.tsx
- packages/mobile/src/screen/register/connect-ledger/index.tsx
- packages/mobile/src/screen/register/connect-ledger/modal.tsx
- packages/mobile/src/screen/sign/sign-modal.tsx
- packages/mobile/src/screen/sign/util/cosmos-ledger-sign.ts
- packages/mobile/src/screen/sign/util/handle-cosmos-sign.ts
- packages/mobile/src/screen/sign/util/ledger-types.ts
- packages/mobile/src/utils/ledger.ts
- Ledger Sign 부분을 제작하였습니다.
- Ledger가 연결되지 않았을 때에는 새롭게 Ledger을 연결할 수 있게 LedgerGrantModal을 띄웠습니다.
> [KM-86] Add ledger sign

- packages/mobile/src/screen/setting/screens/security/permission/index.tsx
- 카메라로 Wallet Connect 연결해서 도메인 보이는거 확인하시면 됩니다
> Remove wallet connect virtual url on Domain setting

- packages/mobile/src/components/pageHeader/header-register.tsx
- packages/mobile/src/components/skeleton/index.tsx
- packages/mobile/src/screen/governance/index.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/dashboard/dashboard.tsx
https://linear.app/chainapsis/issue/KM-137/stake-대시보드-페이지-gov-페이지-스켈레톤-추가
stake 대시보드 페이지, 거버넌스 페이지 스켈레톤을 추가 했습니다.
register 헤더의 간단한 리팩토링을 진행했습니다
> [KM-137] stake 대시보드 페이지, 거버넌스 페이지에 스켈레톤 추가

- packages/mobile/src/components/drawer/index.tsx
- packages/mobile/src/components/dropdown/index.tsx
- packages/mobile/src/components/flat-list/index.tsx
- packages/mobile/src/components/input/reciepient-input/address-book-modal.tsx
- packages/mobile/src/components/modal/suggest-chain.tsx
- packages/mobile/src/components/scroll-view/common-scroll-view.tsx
- packages/mobile/src/components/scroll-view/content-height-aware-scroll-view.tsx
- packages/mobile/src/components/select-modal/index.tsx
- packages/mobile/src/screen/governance/components/select-modal-gov/index.tsx
- packages/mobile/src/screen/governance/list/index.tsx
- packages/mobile/src/screen/home/components/deposit-modal/copy-address-scene.tsx
- packages/mobile/src/screen/home/components/stakeing-chain-select-modal/index.tsx
- packages/mobile/src/screen/home/components/token-found-modal/index.tsx
- packages/mobile/src/screen/register/connect-ledger/index.tsx
- packages/mobile/src/screen/register/enable-chains/index.tsx
- packages/mobile/src/screen/setting/components/contract-address-book-modal/index.tsx
- packages/mobile/src/screen/setting/screens/general/delete-suggest-chain/index.tsx
- packages/mobile/src/screen/setting/screens/general/wallet-connect/index.tsx
- packages/mobile/src/screen/setting/screens/token/manage/index.tsx
- packages/mobile/src/screen/sign/sign-adr36-modal.tsx
- packages/mobile/src/screen/sign/sign-modal.tsx
- packages/mobile/src/screen/staking/validator-list/index.tsx
flat와 scroll view에 indicator 색상을 추가 했습니다
indicator 등 공통설정들을 함께 적용 할 수 있게 컴포넌트로 분리 했습니다
> [KM-139] 라이트모드에서도 스크롤 색이 white일 수 있게 설정

- packages/mobile/src/config.ts
- packages/mobile/src/languages/en.json
- packages/mobile/src/screen/home/app-update-modal.tsx
- packages/mobile/src/screen/home/code-push-update-modal.tsx
- packages/mobile/src/screen/home/index.tsx
- packages/mobile/src/stores/root.tsx
- packages/mobile/src/stores/version/index.ts
- app store에서 버전 체크후 보여주는 app 업데이트 모달
- code push 업데이트 모달을 구현 했습니다
- app update modal은 app store, play store에서 app 버전을 가져와서 비교한뒤 다르면 모달을 보여주게 됩니다
play store 같은경우 api가 따로 없는것 같아서
https://github.com/kimxogus/react-native-version-check/blob/4aa920302d59ce5249d37cbaae969565d18aafd2/packages/react-native-version-check/src/providers/playStore.js#L39-L43
해당 코드를 참고해서 파싱을 하게 했습니다
안정성을 위해서라면 따로 api 서버 하나 만들어서 거기서 체크하는게 더 나을것 같아요
> [KM-124] 강제 업데이트 모달

- packages/mobile/src/screen/home/components/claim-all/index.tsx
claim all 로직이 실제로 수행이 안되는 버그를 수정했습니다.
requester가 RN께 아니라 extension꺼를 쓰고 있어서 생기는 문제 같아서 RN으로 수정했습니다
> [Fix] claim all 동작안되는 버그 수정

- packages/mobile/src/screen/setting/screens/contacts/add/index.tsx
- packages/mobile/src/screen/setting/screens/security/bio-authentication/index.tsx
- packages/mobile/src/screen/setting/screens/security/change-password/index.tsx
- packages/mobile/src/screen/setting/screens/token/add/index.tsx
- packages/mobile/src/screen/wallet/delete/index.tsx
- packages/mobile/src/screen/wallet/show-sensitive/index.tsx
기존의 컨펌버튼을 secondary에서 primary로 색상 변경
token add 페이지에서 하단 패딩이 누락되어 추가했습니다
> [KM-151] 디자인 qa 및 누락사항 구현

- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/home/components/looking-for-chains/index.tsx
- packages/mobile/src/screen/staking/components/validator-card/index.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- packages/mobile/src/screen/staking/validator-detail/delegated-card.tsx
- packages/mobile/src/screen/staking/validator-detail/index.tsx
- packages/mobile/src/screen/staking/validator-detail/unbonding-card.tsx
- packages/mobile/src/screen/staking/validator-list/index.tsx
- packages/mobile/src/screen/wallet/change-name/index.tsx
hoem, stake,select wallet 페이지에 text 및 디자인을 수정 했습니다
> [QA] 전체 qa를 하면서 누락된 부분을 적용 했습니다

- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/governance/index.tsx
- packages/mobile/src/screen/home/components/stakeing-chain-select-modal/index.tsx
- packages/mobile/src/screen/staking/components/validator-item/index.tsx
- staking 탭의 stake 버튼 클릭시 보이는 모달을 디자인에 맞게 스타일을 수정했습니다
- 스테이킹 대시보드에서 jailed 아이콘 색상 변경
- 거버넌스 페이지에서 info modal 추가
- text qa에 맞춰서 일부 텍스트 변경
> [QA] 누락된 디자인과 text qa 사항들을 적용했습니다

- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/unlock/index.tsx
- packages/mobile/src/screen/unlock/migration.tsx
기존 unlock페이지에서 second phrase를 제거했습니다
second phrase를 따로 migration 페이지로 분리 했습니다
> 마이그레이션 페이지의 첫번째, 두번째 phrase를 분리 했습니다

- packages/mobile/src/config.ts
- packages/mobile/src/screen/sign/message-item.tsx
cc9bfed9fb1dc25ee1f2a3857d7bad560f11eedd
-> https://www.notion.so/chainapsis/Mobile-2-0-Design-QA-4d17f1de86764d999f98e6c1bed7ee7f?p=22d33bff3b0448399340937c350d49bb&pm=s 
8730db27ce6c6eb15d44adf9a419096ff4730cc3
-> terra classic도 vote에 보일수 있도록 추가
> [QA] 디자인 qa 적용, terra-classic vote페이지에서 보일수 있게수정

- packages/mobile/src/screen/migration-welcome/components/restart-modal.tsx
> [fix] disable gesture in restart modal

- packages/mobile/src/components/empty-view/index.tsx
- packages/mobile/src/components/input/reciepient-input/address-book-modal.tsx
- packages/mobile/src/components/pageHeader/header-register.tsx
- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/navigation.tsx
- packages/mobile/src/screen/governance/index.tsx
- packages/mobile/src/screen/governance/list/index.tsx
- packages/mobile/src/screen/register/components/scroll-view-register-container.tsx
- packages/mobile/src/screen/register/connect-ledger/index.tsx
- packages/mobile/src/screen/setting/components/contract-address-book-modal/index.tsx
- packages/mobile/src/screen/setting/screens/general/delete-suggest-chain/index.tsx
- packages/mobile/src/screen/setting/screens/security/permission/index.tsx
- packages/mobile/src/screen/setting/screens/security/wallet-connect/index.tsx
- packages/mobile/src/screen/staking/validator-list/index.tsx
- packages/mobile/src/screen/wallet/change-name/index.tsx
- packages/mobile/src/screen/wallet/delete/index.tsx
- packages/mobile/src/screen/wallet/show-sensitive/index.tsx
523e1f1fb163ccfbdcbc7744ea2c888c2e1f60aa
-> 헤더가 h3일때 렛져연결하는 페이지의 헤더가 잘리는문제가 있어서 일부만 h4로 교체함 https://chainapsis.slack.com/archives/C01RAHVLXFS/p1705056646340439
d213ce5807531f36686f5988b851e90ab9623019
-> 스테이킹한 자산이 없을때 거버넌스 페이지가 안보이는 버그 수정
3abbd7bc27923db6f35f4f638f95b10fef4b5b28
-> 연결한 웹사이트 페이지에서 url이 길때 overflow되는 문제 수정
4479b18ac54f744d74a50a9c25ddb26054edbfc5
-> all proposals에서 embed된 체인중에서 스테이킹이 가능 체인을 다 보여줄 수 있게 수정
0a96b6d6f48fab728761c491ee9b95eb23cab916
-> 월렛커넥트 empty text 수정
cd51af8aff85e0b22f2951a131fcf1b58de1a9ce
-> select wallet 관련 페이지들(delete,change-password, show-sensitive)이 레지스터 페이지 처럼 될 수 있게 수정
b961b9a9ba745c84a4bbfcf72237649a38568daa
-> empty text에서 chilren이 props로 올때 text 컴포넌트 안에 있어서 안드로이드에서 뷰가 제대로 보이지 않는 버그가 있어서 수정함
a3c7210a0a6c9fb5b48f0a7f6863427a47035779
-> …
> [QA] qa 사항들과 기타 버그들 수정

- packages/mobile/src/components/input/fee-control/transaction-fee-modal.tsx
- packages/mobile/src/components/input/reciepient-input/address-book-modal.tsx
- packages/mobile/src/screen/migration-welcome/components/restart-modal.tsx
- packages/mobile/src/screen/migration-welcome/index.tsx
- packages/mobile/src/screen/register/welcome/index.tsx
- packages/mobile/src/screen/sign/sign-modal.tsx
- packages/mobile/src/screen/unlock/migration.tsx
dcd96345e36222dceb116d9dcf17b2eb7f74b20e
-> https://www.notion.so/chainapsis/fa9d073e55df4ce7a065bf6dcc4b271e?v=a126e5dbab1348b29bd0bfca96f5b009&p=276c3646ef144a509b41ffb46c77b2c7&pm=s 
Fee Set 모달, Address book 타이틀 스타일 수정
4a72026b89b7e2b7e84fed623ac0a05463fe81fa
-> https://www.notion.so/chainapsis/fa9d073e55df4ce7a065bf6dcc4b271e?v=a126e5dbab1348b29bd0bfca96f5b009&p=c6fe081b39f3418d95c7f7478a43aa79&pm=s, https://www.notion.so/chainapsis/fa9d073e55df4ce7a065bf6dcc4b271e?v=a126e5dbab1348b29bd0bfca96f5b009&p=e80e58263c2b4d42b533fe11078beb75&pm=s
welcome 페이지에서 보이는 로켓 lottie border radius 28로 수정
1606f2434dc15db974cced12b1f185b0ed290cc5
->https://www.notion.so/chainapsis/fa9d073e55df4ce7a065bf6dcc4b271e?v=a126e5dbab1348b29bd0bfca96f5b009&p=3069e5e00e7949e1a95e618407822660&pm=s, …
> [QA] 디자인 qa 적용

- packages/mobile/src/languages/en.json
- packages/mobile/src/screen/register/enable-chains/index.tsx
- packages/mobile/src/screen/send/select-asset/index.tsx
Import Existing Wallet 오타수정
Send 페이지에서 체크박스에 "No available asset"을 "Hide IBC token"으로 변경 
-> a975335c60f0fbbfd7c08a5621ed0c789330ed44
Enable chain 페이지에서 select all 체크박스 클릭안되는 버그 수정
->886c2a84067dd93e72cd63589fda08dcc11ba49d
> [QA] qa 적용

- packages/mobile/src/stores/governance/v1/proposal.ts
> Fix proposal title bug

- packages/background/src/phishing-list/handler.ts
- packages/background/src/phishing-list/init.ts
- packages/background/src/phishing-list/messages.ts
- packages/mobile/src/hooks/confirm/provider.tsx
- packages/mobile/src/hooks/confirm/types.ts
- packages/mobile/src/injected/index.ts
- packages/mobile/src/screen/web/webpage.tsx
- Add `CheckURLIsPhishingOnMobileMsg`, `URLTempAllowOnMobileMsg` message on Background
- Add `yesText` on confirm modal component.
- Add phishing logic on webpage component.
> Add phishing list on mobile

- packages/extension/src/pages/ibc-swap/index.tsx
> [KEPLR-223] Add `Powered by Skip API` on ibc swap page

- packages/mobile/src/screen/register/enable-chains/index.tsx
- Fix name to Noble(USDC) from Noble
- Add chain Noble as  default enabled chain
- minor bug fix
> Change enabled default chain

- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/sign/components/high-fee-warning/index.tsx
- packages/mobile/src/screen/sign/sign-modal.tsx
> [KEPLR-265] Show warning when fee is high(Mobile)

- packages/mobile/src/languages/en.json
- packages/mobile/src/languages/ko.json
- packages/mobile/src/screen/governance/list/index.tsx
> [KEPLR-268] Add warning box when voting cosmos hub

- apps/mobile/src/languages/en.json
- apps/mobile/src/languages/ko.json
- apps/mobile/src/navigation.tsx
> [KEPLR-282, Mobile] Add bottom navigation label

- packages/stores/src/account/cosmos.ts
Add `/stratos.crypto.v1.ethsecp256k1.PubKey`
> Add stratos pubkey support

- apps/mobile/src/components/modal/add-token.tsx
- apps/mobile/src/components/modal/suggest-chain.tsx
- apps/mobile/src/languages/en.json
- apps/mobile/src/languages/ko.json
- apps/mobile/src/stores/wallet-connect/index.tsx
- apps/mobile/src/stores/wallet-connect/schema.ts
- packages/wc-client-example/src/app.tsx
- packages/wc-client/src/index.ts
- packages/wc-qrcode-modal/src/index.tsx
https://github.com/chainapsis/keplr-wallet/pull/1075 <- PR이 `prepare-mobile-merge`에 머지하려고 해서 다시 올립니다!
> [KEPLR-243] Add suggest token/chain on wallet connect

- apps/mobile/src/screen/web/search/index.tsx
> [KEPLR-302, Mobile] Add minimum height on search input on web browser screen

- apps/mobile/babel.config.js
- apps/mobile/src/languages/en.json
- apps/mobile/src/languages/ko.json
- apps/mobile/src/screen/home/available.tsx
- apps/mobile/src/screen/home/components/token/index.tsx
- apps/mobile/src/screen/setting/screens/general/general.tsx
- apps/mobile/src/stores/root.tsx
- apps/mobile/src/stores/ui-config/index.ts
> [KEPLR-295, Mobile] Add price percentage change rate on Home screen

- apps/mobile/src/languages/en.json
- apps/mobile/src/languages/ko.json
- apps/mobile/src/screen/home/components/new-chain-modal/index.tsx
- apps/mobile/src/screen/home/components/update-note-modal/index.tsx
- apps/mobile/src/screen/home/index.tsx
- apps/mobile/src/stores/ui-config/changelog.ts
- apps/mobile/src/stores/ui-config/index.ts
- apps/mobile/src/stores/ui-config/new-chain.ts
> [KEPLR-318 `Mobile`] Add update note, new chain Modal

- apps/mobile/android/app/src/main/AndroidManifest.xml
- apps/mobile/src/components/modal/copy-address-modal.tsx
- apps/mobile/src/components/modal/index.ts
- apps/mobile/src/navigation.tsx
- apps/mobile/src/screen/home/index.tsx
- apps/mobile/src/stores/deep-link/index.tsx
> [KEPLR-359, `Mobile`] Add show address modal deep link

- apps/extension/src/pages/sign/components/eth-tx/render/execute-contract.tsx
- apps/extension/src/pages/sign/components/eth-tx/render/send-token.tsx
- apps/extension/src/pages/sign/ethereum/view.tsx
> Fix an issue that EVM tx failed because of `gasPrice` is injected into tx with `maxFeePerGas`

- packages/provider/src/inject.ts
https://eip6963.org/
여기서 this 관련 문제가 발생하기 때문에
그냥 method를 다 arrow function으로 바꿈
> [KEPLR-453] injected keplr의 ethereum 관련 method를 arrow function으로 바꾸기

- apps/extension/src/pages/permission/basic-access/index.tsx
|   **Extension**  |  **Extension - SidePanel**   |
| --- | --- |
| ![Sep-20-2024 14-03-25](https://github.com/user-attachments/assets/acc2e106-31d5-4074-901b-d7ffb6a33e2e)  | ![Sep-20-2024 14-04-42](https://github.com/user-attachments/assets/ef6046b7-9ff2-4af9-8f52-db6a5a4c128f)  |
> [KEPLR-306] Add scrollbar to Requesting Connection page

- apps/extension/src/pages/ibc-swap/components/swap-fee-info/index.tsx
useLayoutEffect의 dependencies에 들어간 값들의 변경이 감지가 되지 않아 로직이 정상적으로 실행되지 않았고, 이를 해결하기 위해 useLayoutEffect 안에서 autorun으로 해당 로직을 감싸줬습니다.
> [KEPLR-366] Resolve issue with swap fee currency not being set properly

- apps/extension/src/components/button/cancel-icon.tsx
- apps/extension/src/components/button/index.ts
- apps/extension/src/pages/permission/basic-access-for-evm/index.tsx
- apps/extension/src/pages/permission/basic-access-for-starknet/index.tsx
- apps/extension/src/pages/permission/basic-access/index.tsx
- apps/extension/src/pages/permission/get-chain-infos/index.tsx
- apps/extension/src/pages/sign/cosmos/adr36.tsx
- apps/extension/src/pages/sign/cosmos/icns/index.tsx
- apps/extension/src/pages/sign/cosmos/tx/view.tsx
- apps/extension/src/pages/sign/ethereum/view.tsx
- apps/extension/src/pages/starknet/sign/message/view.tsx
- apps/extension/src/pages/starknet/sign/tx/view.tsx
- apps/extension/src/pages/suggest-chain/index.tsx
- packages/stores-core/src/core/interaction/chain-suggest.ts
- packages/stores-core/src/core/interaction/eth-sign.ts
- packages/stores-core/src/core/interaction/icns.ts
- packages/stores-core/src/core/interaction/interaction.ts
- packages/stores-core/src/core/interaction/permission.ts
- packages/stores-core/src/core/interaction/sign.ts
- packages/stores-core/src/core/interaction/starknet-sign-message.ts
- packages/stores-core/src/core/interaction/starknet-sign-tx.ts
- Add CancelIcon and replace XMarkIcon on cancel button with CancelIcon
- Add `isObsoleteInteractionApproved` method to InteractionStore class and classes embedding its instance to show the loading spinner only on approval
> [KEPLR-503] QA2

- apps/extension/src/pages/permission/basic-access-for-evm/index.tsx
- apps/extension/src/pages/permission/basic-access-for-starknet/index.tsx
- apps/extension/src/pages/permission/basic-access/index.tsx
- apps/extension/src/pages/permission/get-chain-infos/index.tsx
- apps/extension/src/pages/sign/cosmos/adr36.tsx
- apps/extension/src/pages/sign/cosmos/icns/index.tsx
- apps/extension/src/pages/sign/cosmos/tx/view.tsx
- apps/extension/src/pages/sign/ethereum/view.tsx
- apps/extension/src/pages/starknet/sign/message/view.tsx
- apps/extension/src/pages/starknet/sign/tx/view.tsx
- apps/extension/src/pages/suggest-chain/index.tsx
- Light mode color for cancel button was not properly set.
> Change cancel button color on light mode

- docs/api/secretjs.md
- docs/api/suggest-chain.md
These changes improve the documentation's readability and professional appearance by:
- Correcting subject-verb agreement
- Fixing spelling errors
- Adding missing articles
- Ensuring consistent grammar throughout the documentation
> Grammar and Spelling Corrections

- apps/extension/src/hooks/use-get-search-chains.ts
- apps/extension/src/pages/main/components/deposit-modal/copy-address-scene.tsx
> [KEPLR-689] looking for chains에서 케플러에 suggest chain으로 추가되었지만 keplr-chain-registry에는 없는 체인은 뜨지않는 버그 수정

- apps/extension/scripts/lerna-lifecyle-version.mjs
- packages/provider-extension/scripts/lerna-lifecyle-version.mjs
- scripts/lerna-lifecyle-check-version.mjs
Corrected variable name sementic to semantic in lifecycle scripts for clarity.
> Fix Typo Error in Variable Name: sementic to semantic

- apps/extension/src/components/icon/coins-plus-outline.tsx
- apps/extension/src/components/icon/index.tsx
- apps/extension/src/components/transition/vertical-collapse/collapse.tsx
- apps/extension/src/components/transition/vertical-collapse/types.ts
- apps/extension/src/components/transition/vertical-size/internal/context.ts
- apps/extension/src/hooks/claim/index.ts
- apps/extension/src/hooks/claim/use-claim-all-each-state.ts
- apps/extension/src/hooks/claim/use-cosmos-claim-rewards.ts
- apps/extension/src/hooks/claim/use-starknet-claim-rewards.ts
- apps/extension/src/pages/main/components/claim-all/index.tsx
- apps/extension/src/pages/main/index.tsx
- apps/extension/src/pages/main/staked.tsx
- apps/extension/src/pages/main/token-detail/modal.tsx
- apps/extension/src/pages/main/token-detail/staked-balance.tsx
- apps/extension/src/stores/huge-queries/index.ts
- apps/mobile/src/screen/token-detail/components/staked-balance.tsx
- packages/background/src/keyring-starknet/handler.ts
- packages/background/src/keyring-starknet/init.ts
- packages/background/src/keyring-starknet/messages.ts
- packages/background/src/keyring-starknet/service.ts
- packages/stores-starknet/src/account/base.ts
- packages/stores-starknet/src/account/internal.ts
- packages/stores-starknet/src/queries/index.ts
- packages/stores-starknet/src/queries/staking/apr.ts
- packages/stores-starknet/src/queries/staking/index.ts
- packages/stores-starknet/src/queries/staking/pool-member-info.ts
- packages/stores-starknet/src/queries/staking/types.ts
- packages/stores-starknet/src/queries/staking/validators.ts
- starknet staking 관련 쿼리 추가 (apr 계산, 밸리데이터 리스트, staking pool contract - staking info)
- 생태계별 claim 함수를 훅으로 분리 
- modular chian info에 기반해서 분기 처리 (향후 비트코인 등 추가 고려)
- hugeQueriesStore에 starknet staking 쿼리 추가
- 백그라운드 메시지 `PrivilegeStarknetSignClaimRewardsMsg` 추가
> Starknet Staking Support

- apps/extension/src/pages/main/staked.tsx
- apps/extension/src/stores/huge-queries/index.ts
- starknet unbonding 시간 표기를 endur.fi와 마찬가지로 단위 시간 아래 소숫점을 버리도록 변경했습니다.
> Starknet staking - QA

- apps/extension/webpack.config.js
- package.json
- packages/crypto/package.json
- packages/crypto/src/key.spec.ts
- packages/crypto/src/key.ts
- yarn.lock
- Test bitcoin compatible addresses (legacy, native segwit, taproot)
> Bitcoin address test

- apps/extension/src/pages/register/enable-chains/index.tsx
- apps/extension/src/pages/register/new-mnemonic/index.tsx
- apps/extension/src/pages/register/recover-mnemonic/index.tsx
- apps/extension/src/pages/register/utils/check-button-position-and-scroll-to-button.ts
-   특정 버튼이 viewport에 없을 경우 해당 버튼으로 이동 하는 함수인checkButtonPositionAndScrollToButton를 구현했습니다.
- enable-chains에서 chainItem들이 다 렌더링될때 까지 임의로 500ms 기다린뒤 checkButtonPositionAndScrollToButton 실행하도록 적용
- addvaced가 있는 페이지의 경우 해당 버튼을 클릭했을때 하단 버튼이 내려갔을경우 해당 버튼으로 스크롤이 이동되도록  checkButtonPositionAndScrollToButton을 적용
> Wallet Onboarding web page 개선

- apps/extension/src/components/icon/article-outline.tsx
- apps/extension/src/components/icon/index.tsx
- apps/extension/src/languages/en.json
- apps/extension/src/languages/ko.json
- apps/extension/src/languages/zh-cn.json
- apps/extension/src/pages/send/amount/swap-fee-info/index.tsx
- https://linear.app/chainapsis/issue/KEPLR-734/%5Bext%5D-%5B%EA%B0%9C%EB%B0%9C%5D-evm-%EB%B8%8C%EB%A6%BF%EC%A7%80-%EC%A7%80%EC%9B%90-%EC%8B%9C-%ED%95%84%EC%9A%94%ED%95%9C-fee-%EA%B4%80%EB%A0%A8-ui
- 추가된 "You will receive" 뷰 추가
> "You will receive" 부분 추가

- .github/workflows/chromatic.yml
- .github/workflows/lint.yml
- .github/workflows/mobile-publish.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
https://github.com/actions/runner-images/issues/11101
> Bump Ubuntu to v24.04 for GitHub Actions

- docs/docs/mobile/deeplink.md
- docs/sidebars.ts
Preview :
https://keplr-wallet-extension-git-editaah-keplr-913-chainapsis.vercel.app/api/mobile/deeplink
> Add Deeplinking page to Keplr Docs

- apps/extension/src/languages/en.json
- apps/extension/src/languages/ko.json
- apps/extension/src/languages/zh-cn.json
- apps/extension/src/pages/ibc-swap/components/swap-fee-info/index.tsx
- apps/extension/src/pages/send/amount/index.tsx
- apps/extension/src/pages/send/amount/swap-fee-info/index.tsx
- bridge fee intl 추가 및 warningGuideBox text 수정
- WarningGuideBox에서 ibc 토큰의 경우 metadata hide 적용
> evm bridge qa 수정 사항

- docs/docs/getting-started/connect-to-keplr.mdx
Preview: https://keplr-wallet-extension-git-editaahn-keplr-923-chainapsis.vercel.app/api/getting-started/connect-to-keplr#keplr-fallback
> Keplr Docs Update: KeplrFallback

- apps/extension/src/pages/main/components/menu-bar/index.tsx
- 왼쪽 메뉴 사이드 바에서 manage asset 과 체인추가 제거 버튼 위치 변경
> 사이드바에서 버튼 위치 수정 

- apps/extension/src/languages/en.json
- apps/extension/src/pages/manage-view-asset-token-list/index.tsx
- apps/extension/src/pages/register/enable-chains/components/chain-item.tsx
- Token item의 이미지랑 denom사이에 간격 수정
- tokens text에 plural 적용
> select chains 추가 qa 적용 

- apps/extension/src/pages/register/enable-chains/components/next-step-chain-item.tsx
- React import가 이상한곳에서 import되고 있는 버그 수정
> [fix] to fix wrong path to import React

- packages/chain-validator/src/feature.spec.ts
- packages/chain-validator/src/feature.ts
- packages/stores-ibc/src/currency-registrar.ts
- packages/stores/src/query/cosmos/ibc/client-state-v2.ts
- packages/stores/src/query/cosmos/ibc/denom-trace.ts
- packages/stores/src/query/cosmos/ibc/types.ts
- packages/stores/src/query/cosmos/queries.ts
일단 테스트를 하려면 ethereum sepolia를 추가해야하기 때문에 extension의 config.ts에 아래의 체인 정보를 추가해야함
provider testnet은 메인 페이지의 search에서 provider 검색해서 추가
erc20 contract info는 extension의 Add Token에서 수동으로 추가해야함
테스트를 위한 토큰은 슬랙으로 저한테 요청하면 드림
```
{
rpc: "https://sepolia.drpc.org",
rest: "https://sepolia.drpc.org",
chainId: "eip155:11155111",
bip44: {
coinType: 60,
},
chainName: "Sepolia",
stakeCurrency: {
coinDenom: "ETH",
coinMinimalDenom: "ETH",
coinDecimals: 18,
},
currencies: [
{
coinDenom: "ETH",
coinMinimalDenom: "ETH",
coinDecimals: 18,
},
],
feeCurrencies: [
{
coinDenom: "ETH",
coinMinimalDenom: "ETH",
coinDecimals: 18,
},
],
evm: {
chainId: 11155111,
rpc: "https://sepolia.drpc.org",
websocket: "wss://sepolia.drpc.org",
},
features: ["eth-address-gen", "eth-key-sign"],
beta: true,
}
```
변경사항
- features에 …
> Initial support for ibc eureka currency registrar

- apps/extension/src/pages/main/components/token-found-modal/index.tsx
- apps/extension/src/pages/register/enable-chains/components/chain-item.tsx
- apps/extension/src/pages/register/enable-chains/index.tsx
- apps/extension/src/stores/huge-queries/index.ts
- select chains 페이지의 비트코인 항목 하위 요소로 주소별 자산 보유량 표시 추가
- select chains 페이지에서 비트코인도 보유 금액으로 정렬되도록 추가
- Token found 모달의 비트코인 항목 하위 요소에 주소 태그 추가
> Bitcoin Design Changes2

- apps/extension/src/config.ts
- apps/extension/src/hooks/bitcoin/use-psbt-validate.ts
- apps/extension/src/languages/en.json
- apps/extension/src/languages/ko.json
- apps/extension/src/pages/bitcoin/sign/tx/view.tsx
- apps/extension/src/pages/main/available.tsx
- apps/extension/src/pages/main/components/token-found-modal/index.tsx
- apps/extension/src/pages/main/components/token/index.tsx
- apps/extension/src/pages/register/enable-chains/components/chain-item.tsx
- packages/provider/src/inject.ts
- Payment type을 토큰이 아닌 체인 정보에서 가져오도록 수정
- PSBT output script decoding 추가
- PSBT total spend, estimated network fee 계산식 수정
- 비트코인 token item에서 copy address 버튼 노출
> [QA] Support Bitcoin - QA 1

- apps/extension/src/components/input/amount-input/input.tsx
- apps/extension/src/pages/bitcoin/components/address-book-modal/index.tsx
- apps/extension/src/pages/bitcoin/components/address-item/index.tsx
- apps/extension/src/pages/bitcoin/components/input/amount-input/input.tsx
- apps/extension/src/pages/main/token-detail/modal.tsx
- apps/extension/src/pages/register/enable-chains/index.tsx
- apps/extension/src/pages/setting/contacts/add/index.tsx
- apps/extension/src/pages/starknet/components/input/amount-input/input.tsx
- packages/hooks-bitcoin/src/tx/amount.ts
- packages/hooks-starknet/src/tx/amount.ts
- packages/hooks/src/tx/amount.ts
- Bitcoin Address Book 모달에서 내 계정에 Payment type 태그 추가
- Send 페이지에서 amount가 Integer 최대값을 넘어가면 Reset Cache 오류 화면이 되는 이슈 해결
- Contacts 페이지에서 비트코인 주소 추가 안되는 이슈 해결
- Enable chains 페이지에서 Native Segwit 계정에만 밸런스 있을 때 자동 enable 되지 않는 이슈 해결
> [QA] Support Bitcoin - QA 3

- apps/extension/src/config.ts
- apps/extension/src/hooks/bitcoin/use-psbt-validate.ts
- apps/extension/src/languages/en.json
- apps/extension/src/languages/ko.json
- apps/extension/src/languages/zh-cn.json
- apps/extension/src/pages/bitcoin/components/guide-box/index.tsx
- apps/extension/src/pages/bitcoin/send/index.tsx
- apps/extension/src/pages/bitcoin/sign/tx/view.tsx
- apps/extension/src/pages/main/components/token-found-modal/index.tsx
- apps/extension/src/pages/register/enable-chains/index.tsx
- packages/background/src/keyring-bitcoin/handler.ts
- packages/background/src/keyring-bitcoin/messages.ts
- packages/background/src/keyring-bitcoin/service.ts
- packages/background/src/keyring-mnemonic/service.ts
- packages/background/src/keyring-private-key/service.ts
- packages/background/src/keyring/service.ts
- packages/background/src/keyring/types.ts
- packages/provider-extension/src/keplr.ts
- packages/provider-mock/src/mock.ts
- packages/provider/src/core.ts
- packages/provider/src/inject.ts
- packages/stores-core/src/core/interaction/bitcoin-sign-tx.ts
- packages/types/src/wallet/bitcoin.ts
- packages/types/src/wallet/keplr.ts
- packages/wc-client/src/index.ts
- `signPsbt`, `signPsbts` 메소드 파라미터로 `SignPsbtOptions` 받을 수 있도록 수정
- PSBT 서명 페이지에서 validation 에러 발생시 에러메시지 보여주도록 수정
- Token found 모달에서 payment type 잘못 보이는 이슈 해결
- Enable chains 페이지에서 비트코인 메인넷 세번째로 보여주도록 수정
> [QA] Support Bitcoin - QA 4

- apps/extension/src/pages/register/enable-chains/index.tsx
- ledger 연결해서 체인 활성화하는 것만 신경쓰다가 비활성화 안되는 문제를 놓쳐서 해당 사항 해결했습니다.
- 기존에 ledger 사용할 때 disable하려는 의도가 없던 체인도 간혹 disable되는 경우가 있었는데 각 단계별로 해당되는 체인만 활성화/비활성화하도록 로직 추가해서 해당 문제도 해결됐습니다.
> Fix deactivation of non-cosmos chains not working with ledger

- apps/extension/src/stores/ui-config/manage-view-asset-token.ts
- 이전에 구현 사항에서 isDisabledTokenSearched 함수(home에서 검색 했을때 해당 token이 manage view asset에서 disabled 되어있는지 확인 하는 함수)가 coinMinimalDenom과 chainIdentifier만 비교 해서 원하는 동작이 되지 않았던 버그 수정
> [fix] isDisabledTokenSearched 로직 수정

- apps/extension/src/languages/en.json
- apps/extension/src/languages/ko.json
- apps/extension/src/languages/zh-cn.json
- connect ledger 단계에 bitcoin 관련 내용 추가
- non-native chain 추가/제거 페이지 이동 버튼에 한국어 번역 추가
> Minor Intl message changes

- apps/extension/src/pages/main/components/token-found-modal/index.tsx
- packages/background/src/token-scan/service.ts
- token found modal에서 비트코인이 일부 주소 형식에서만 발견되었을 때, 다른 주소 형식을 함께 활성화하지 않는 오류 해결
- `calculateTokenScan`에서 `linkedChainKey`로 연결된 체인들을 함께 스캔하도록 추가, 
- `getTokenScans`에서 `linkedChainKey`로 스캔 정보를 병합하던 로직을 제거하고 이전 코드로 되돌렸습니다.
> Fix issue in Token Found Modal

- apps/extension/src/pages/main/staked.tsx
- apps/extension/src/stores/huge-queries/index.ts
- apps/extension/src/utils/get-babylon-unbonding-remaining-time.ts
Dashboard, Mobile에도 적용된 로직과 동일
> babylon unbonding time estimation

- apps/extension/src/background/background.ts
- apps/extension/src/components/contract-address-book-modal/index.tsx
- apps/extension/src/components/contract-item/index.tsx
- apps/extension/src/config.ts
- apps/extension/src/config.ui.ts
- apps/extension/src/pages/setting/token/add/index.tsx
- apps/extension/src/stores/root.tsx
- apps/extension/src/stores/token-contracts/contracts.ts
- packages/background/src/index.ts
- packages/background/src/token-cw20/service.ts
- packages/stores-starknet/src/queries/token-contracts.ts
- 백그라운드에 저장된 Custom CW20 토큰들의 `coinImageUrl`, `coingeckoId` 를 Keplr contract registry에 있는 데이터로 24시간마다 업데이트 시키도록 변경
- 새로운 CW20 토큰이 추가될 때도 업데이트 함
- Contract Addresses 모달에서 추가되는 토큰은 `coinImageUrl`, `coingeckoId` 데이터 같이 추가되도록 변경
> Make custom token image url, coingecko id updated automatically

- apps/extension/src/languages/en.json
- apps/extension/src/languages/ko.json
- apps/extension/src/languages/zh-cn.json
- apps/extension/src/pages/sign/components/messages/registry.tsx
- apps/extension/src/pages/sign/components/messages/render/claim-btc-delegation-reward.tsx
- apps/extension/src/pages/sign/components/messages/render/create-btc-delegation.tsx
- packages/stores/src/query/cosmos/queries.ts
- packages/stores/src/query/cosmos/staking/babylon-btc-delegation-reward.ts
- packages/stores/src/query/cosmos/staking/index.ts
- packages/stores/src/query/cosmos/staking/types.ts
- 서명 페이지에서 `/babylon.incentive.MsgWithdrawReward` 메시지 처리를 위한 ui를 추가했습니다.
> Handle `/babylon.incentive.MsgWithdrawReward`

- apps/extension/src/pages/ibc-swap/index.tsx
- packages/hooks/src/tx/fee.ts
- EVM swap tx에 불필요한 프로퍼티가 포함되어 있어서 이를 제거합니다
- BNB 체인은 EIP-1559를 따르지면 fee market 시스템은 없어서 gas price만을 사용하도록 수정합니다
> Fix swap failing on BNB chain

- apps/extension/src/pages/ibc-swap/hooks/use-swap-analytics.ts
- apps/extension/src/pages/ibc-swap/index.tsx
- apps/extension/src/pages/send/amount/index.tsx
- apps/extension/src/stores/root.tsx
- apps/hooks-internal/src/ibc-swap/amount.ts
- apps/hooks-internal/src/ibc-swap/use.ts
- apps/stores-internal/src/skip/ibc-swap.ts
- apps/stores-internal/src/skip/msgs-direct.ts
- apps/stores-internal/src/skip/queries.ts
- route query 응답을 사용하는 부분을 msgs-direct query 응답이 내려주는 route 데이터로 대체
- quote -> tx 생성까지 한 번의 msgs-direct query로 진행하도록 수정
> Replace skip route query to msgs-direct query

- apps/extension/src/pages/main/available.tsx
- apps/extension/src/pages/main/hooks/use-balance-analytics.ts
- The Amplitude userId is hashed to preserve user privacy
- Minimized event calls by sending only once after initialized, when values are changed
> Add analytics for btc, eth, erc20 balances

- docs/.gitignore
- docs/docs/guide/suggest-chain.md
- docs/docs/intro/index.md
- docs/docusaurus.config.ts
- docs/package.json
- docs/src/css/custom.css
- docs/src/pages/index.tsx
- docs/yarn.lock
- integrated Algolia search functionality into the documentation site (+Vercel deployment configuration with environment variable support)
- automatically redirect users to the document page (`/api/intro`) instead of showing a hero banner.
- added padding bottom to the sidebar
- fixed a typo ("wallets" → "wallet")
[preview](https://keplr-wallet-extension-git-editaahn-keplr-1140-keplrwallet.vercel.app/)
> Keplr Docs Improvement - phase 1

- packages/hooks/src/tx/fee.ts
- 여전히 멤풀에 펜딩상태로 걸리는 문제가 발생하여 아래와 같은 변경사항을 적용하였습니다.
- base fee margin, priority fee percentiles 상향 조정
- priority fee 상한 20 gwei 설정
- priority fee 관련 오류 묶어서 처리
> Adjust eth fee percentiles

- apps/extension/src/pages/main/token-detail/mint-photon-button.tsx
- apps/extension/src/pages/main/token-detail/modal.tsx
- apps/extension/src/pages/sign/cosmos/tx/view.tsx
- packages/hooks/src/tx/fee.ts
- mintPhoton 버튼 추가
- atom one 체인에서 fee를 photon으로 강제 하도록 수정 했습니다
> mintPhoton 버튼 추가 및 atom one 체인에서 fee를 photon으로 강제 하도록 수정
